'use client';

import { useState, useEffect, useMemo } from 'react';
import Link from 'next/link';
import { formatTimeAgoLocale } from '@/lib/locale';

// ─── English Labels ────────────────────────────────────────────
const IMPACT_COLORS: Record<string, string> = { bullish: 'var(--bull)', bearish: 'var(--bear)', neutral: 'var(--gold)' };
const SENTIMENT_LABELS: Record<string, string> = { bullish: 'Bullish', bearish: 'Bearish', neutral: 'Neutral' };
const RISK_LABELS: Record<string, string> = { low: 'Low', medium: 'Medium', high: 'High', extreme: 'Extreme' };
const TIMEFRAME_LABELS: Record<string, string> = { intraday: 'Intraday', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly', quarterly: 'Quarterly' };

// ─── Types ──────────────────────────────────────────────────────

interface Analysis {
  id: string; title: string; slug: string; assetClass: string;
  analysisType: string; timeFrame: string; riskLevel: string;
  sentiment: string; confidenceScore: number; priceTarget: any;
  summary?: string; publishedAt: string | null; validUntil: string | null; createdAt: string;
}

interface CategoryDef {
  id: string; nameEn: string; icon: string;
  color: string; colorBg: string; colorBorder: string;
}

interface Props {
  category: CategoryDef;
  initialAnalyses: Analysis[];
}

export default function EnCategoryReportsPageClient({ category, initialAnalyses }: Props) {
  const [mounted, setMounted] = useState(false);
  const [page, setPage] = useState(1);
  const PER_PAGE = 12;

  useEffect(() => { setMounted(true); }, []);
  useEffect(() => { window.scrollTo(0, 0); }, []);

  const allAnalyses = initialAnalyses;
  const pagedAnalyses = useMemo(() => allAnalyses.slice(0, page * PER_PAGE), [allAnalyses, page]);
  const hasMore = pagedAnalyses.length < allAnalyses.length;

  return (
    <main className="min-h-screen pb-mobile-safe" dir="ltr">
      {/* Header */}
      <div className="relative" style={{ padding: '32px 0 0' }}>
        <div className="max-w-[1280px] mx-auto" style={{ paddingInline: 'clamp(16px, 3vw, 48px)' }}>
          <div className="glass-card" style={{ padding: '24px 32px', background: `linear-gradient(135deg, ${category.colorBg}, rgba(0,229,255,.02))` }}>
            <div className="flex items-center justify-between flex-wrap gap-4">
              <div className="flex items-center gap-3">
                <Link href="/en/reports" className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg transition-all" style={{ background: 'var(--bg4)', border: '1px solid var(--border)', color: 'var(--text3)' }}>
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="9 18 15 12 9 6" /></svg>
                  Back
                </Link>
                <div style={{
                  width: '44px', height: '44px', borderRadius: '12px',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  background: category.colorBg, border: `1px solid ${category.colorBorder}`,
                  fontSize: '22px',
                }}>
                  {category.icon}
                </div>
                <div>
                  <h1 className="text-2xl font-bold" style={{ color: 'var(--text-head, var(--text))' }}>{category.nameEn}</h1>
                </div>
                <span className="text-[11px] px-3 py-1 rounded-full font-semibold" style={{
                  background: category.colorBg, color: category.color,
                  border: `1px solid ${category.colorBorder}`,
                }}>
                  {allAnalyses.length} {allAnalyses.length === 1 ? 'report' : 'reports'}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Reports Grid */}
      <div className="max-w-[1280px] mx-auto py-6" style={{ paddingInline: 'clamp(16px, 3vw, 48px)' }}>
        {allAnalyses.length === 0 ? (
          <div className="glass-card flex items-center justify-center" style={{ padding: '64px', minHeight: '300px' }}>
            <div className="text-center">
              <div style={{ fontSize: '48px', marginBottom: '12px' }}>{category.icon}</div>
              <p className="text-sm font-bold mb-2" style={{ color: 'var(--text2)' }}>No reports in {category.nameEn} yet</p>
              <p className="text-xs" style={{ color: 'var(--text3)' }}>Reports are automatically generated by AI</p>
              <Link href="/en/reports" className="inline-block mt-4 px-4 py-2 rounded-lg text-xs" style={{ background: 'var(--cyan2)', color: 'var(--cyan)', border: '1px solid rgba(0,229,255,.15)' }}>
                Back to Reports
              </Link>
            </div>
          </div>
        ) : (
          <>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {pagedAnalyses.map((analysis) => (
                <Link
                  key={analysis.id}
                  href={`/en/reports/${analysis.slug}`}
                  className="glass-card group transition-all duration-300 hover:-translate-y-1 block"
                  style={{
                    padding: '16px',
                    borderLeft: `3px solid ${category.color}`,
                    textDecoration: 'none',
                  }}
                >
                  {/* Tags */}
                  <div className="flex items-center gap-2 mb-2 flex-wrap">
                    <span className="text-[9px] px-2 py-0.5 rounded-full font-semibold" style={{
                      background: category.colorBg, color: category.color,
                      border: `1px solid ${category.colorBorder}`,
                    }}>{category.nameEn}</span>
                    <span className="text-[9px] px-2 py-0.5 rounded-full" style={{ background: 'var(--cyan2)', color: 'var(--cyan)', border: '1px solid rgba(0,229,255,.12)' }}>
                      {TIMEFRAME_LABELS[analysis.timeFrame] || analysis.timeFrame}
                    </span>
                    {analysis.sentiment && (
                      <span className="text-[9px] px-2 py-0.5 rounded-full font-semibold" style={{
                        background: analysis.sentiment === 'bullish' ? 'var(--bull2)' : analysis.sentiment === 'bearish' ? 'var(--bear2)' : 'var(--gold2)',
                        color: IMPACT_COLORS[analysis.sentiment] || 'var(--gold)',
                      }}>
                        {SENTIMENT_LABELS[analysis.sentiment] || analysis.sentiment}
                      </span>
                    )}
                  </div>

                  {/* Title */}
                  <h4 className="text-[13px] font-bold mb-2 line-clamp-2 group-hover:text-[var(--cyan)] transition-colors" style={{ color: 'var(--text)' }}>
                    {analysis.title}
                  </h4>

                  {/* Summary */}
                  {analysis.summary && (
                    <p className="text-[11px] mb-3 line-clamp-2" style={{ color: 'var(--text2)', lineHeight: '1.7' }}>
                      {analysis.summary}
                    </p>
                  )}

                  {/* Confidence & Risk */}
                  <div className="flex items-center gap-3 mb-2">
                    <div className="flex-1">
                      <div className="flex items-center justify-between mb-1">
                        <span style={{ fontSize: '9px', color: 'var(--text3)' }}>Confidence</span>
                        <span style={{ fontSize: '9px', fontFamily: 'var(--font-jetbrains-mono)', fontWeight: 700, color: analysis.confidenceScore >= 70 ? 'var(--bull)' : analysis.confidenceScore >= 40 ? 'var(--gold)' : 'var(--bear)' }}>
                          {analysis.confidenceScore}%
                        </span>
                      </div>
                      <div className="confidence-bar">
                        <div className="confidence-fill" style={{
                          width: `${analysis.confidenceScore}%`,
                          background: analysis.confidenceScore >= 70 ? 'var(--bull)' : analysis.confidenceScore >= 40 ? 'var(--gold)' : 'var(--bear)',
                        }} />
                      </div>
                    </div>
                    <span className="text-[10px] font-semibold" style={{
                      color: analysis.riskLevel === 'low' ? 'var(--bull)' : analysis.riskLevel === 'high' ? 'var(--bear)' : 'var(--gold)',
                    }}>
                      {RISK_LABELS[analysis.riskLevel] || analysis.riskLevel} Risk
                    </span>
                  </div>

                  {/* Footer */}
                  <div className="flex items-center justify-between pt-2" style={{ borderTop: '1px solid var(--rim, var(--border))' }}>
                    <span style={{ fontSize: '10px', color: 'var(--text3)' }}>
                      {analysis.publishedAt ? formatTimeAgoLocale(analysis.publishedAt, 'en') : ''}
                    </span>
                    <span style={{ fontSize: '11px', fontWeight: 500, color: 'var(--text3)' }} className="group-hover:text-[var(--cyan)] transition-colors flex items-center gap-1">
                      Read Report
                      <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="9 18 15 12 9 6" /></svg>
                    </span>
                  </div>
                </Link>
              ))}
            </div>

            {/* Load More */}
            {hasMore && (
              <div className="flex justify-center mt-8">
                <button
                  onClick={() => setPage(p => p + 1)}
                  className="px-6 py-2.5 rounded-lg text-sm font-semibold transition-all"
                  style={{ background: 'var(--cyan2)', color: 'var(--cyan)', border: '1px solid rgba(0,229,255,.15)' }}
                >
                  Load More ({allAnalyses.length - pagedAnalyses.length} reports remaining)
                </button>
              </div>
            )}
          </>
        )}
      </div>
    </main>
  );
}
