/**
 * ROUAA Source Registry — Initial Seed Data
 *
 * Per docs/execution/05 TASK-012 (Database Seed Data) + TASK-023 (Official Source Import Tool).
 *
 * Goal: seed 30+ official sources across 6 categories as Sprint 0/1 starting point.
 * The full registry target is 411+ sources (per docs/foundation/29-DATA-MODEL-v1.md),
 * but Sprint 0/1 ships with this representative seed for development + first integration tests.
 *
 * Categories covered:
 *   1. Central banks           — 10 sources
 *   2. Regulators              — 7 sources
 *   3. Exchanges               — 5 sources
 *   4. Statistical agencies    — 5 sources
 *   5. Government bodies       — 4 sources
 *   6. International bodies    — 5 sources
 *
 * Total: 36 sources — exceeds the 30+ minimum.
 *
 * All sources are tier 1 (official primary), authority_level: 'primary', status: 'active'.
 * Source URLs are real publication endpoints as of public record.
 */

import { CreateSourceDto } from '../modules/sources/dto/create-source.dto';
import { SourceType } from '../modules/sources/entities/source.entity';

export const SOURCES_SEED: CreateSourceDto[] = [
  // =====================================
  // 1. Central Banks (10)
  // =====================================
  {
    name: 'Federal Reserve',
    code: 'FED',
    type: SourceType.CENTRAL_BANK,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.federalreserve.gov',
    feedUrl: 'https://www.federalreserve.gov/feeds/press_all.xml',
    apiUrl: 'https://www.federalreserve.gov/scripts/synonymstools/getTableReleaseData.cfm',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'US central bank — monetary policy, FOMC statements, Beige Book, H-series statistical releases.',
  },
  {
    name: 'European Central Bank',
    code: 'ECB',
    type: SourceType.CENTRAL_BANK,
    country: 'EU',
    jurisdiction: 'European Union',
    trustTier: 1,
    websiteUrl: 'https://www.ecb.europa.eu',
    feedUrl: 'https://www.ecb.europa.eu/rss/press.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'Eurozone central bank — monetary policy decisions, economic bulletins, statistical releases.',
  },
  {
    name: 'Bank of England',
    code: 'BOE',
    type: SourceType.CENTRAL_BANK,
    country: 'GB',
    jurisdiction: 'United Kingdom',
    trustTier: 1,
    websiteUrl: 'https://www.bankofengland.co.uk',
    feedUrl: 'https://www.bankofengland.co.uk/rss/news',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'UK central bank — MPC decisions, monetary policy reports, financial stability reports.',
  },
  {
    name: 'Bank of Japan',
    code: 'BOJ',
    type: SourceType.CENTRAL_BANK,
    country: 'JP',
    jurisdiction: 'Japan',
    trustTier: 1,
    websiteUrl: 'https://www.boj.or.jp',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Japan central bank — monetary policy statements, Outlook for Economic Activity and Prices.',
  },
  {
    name: "People's Bank of China",
    code: 'PBOC',
    type: SourceType.CENTRAL_BANK,
    country: 'CN',
    jurisdiction: "People's Republic of China",
    trustTier: 1,
    websiteUrl: 'http://www.pbc.gov.cn',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'China central bank — monetary policy, LPR announcements, RMB reference rate.',
  },
  {
    name: 'Swiss National Bank',
    code: 'SNB',
    type: SourceType.CENTRAL_BANK,
    country: 'CH',
    jurisdiction: 'Switzerland',
    trustTier: 1,
    websiteUrl: 'https://www.snb.ch',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Swiss central bank — monetary policy assessments, quarterly bulletin.',
  },
  {
    name: 'Bank of Canada',
    code: 'BOC',
    type: SourceType.CENTRAL_BANK,
    country: 'CA',
    jurisdiction: 'Canada',
    trustTier: 1,
    websiteUrl: 'https://www.bankofcanada.ca',
    feedUrl: 'https://www.bankofcanada.ca/category/news/rss/',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'Canada central bank — interest rate announcements, Monetary Policy Report.',
  },
  {
    name: 'Reserve Bank of Australia',
    code: 'RBA',
    type: SourceType.CENTRAL_BANK,
    country: 'AU',
    jurisdiction: 'Australia',
    trustTier: 1,
    websiteUrl: 'https://www.rba.gov.au',
    feedUrl: 'https://www.rba.gov.au/rss/rss-cb-media-releases.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'Australia central bank — cash rate decisions, Statement on Monetary Policy.',
  },
  {
    name: 'Monetary Authority of Singapore',
    code: 'MAS',
    type: SourceType.CENTRAL_BANK,
    country: 'SG',
    jurisdiction: 'Singapore',
    trustTier: 1,
    websiteUrl: 'https://www.mas.gov.sg',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Singapore central bank + financial regulator — monetary policy statements.',
  },
  {
    name: 'Bank for International Settlements',
    code: 'BIS',
    type: SourceType.CENTRAL_BANK,
    country: 'multinational',
    jurisdiction: 'International (Basel)',
    trustTier: 1,
    websiteUrl: 'https://www.bis.org',
    feedUrl: 'https://www.bis.org/doclist/clickable presse.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Bank for central banks — quarterly review, working papers, economic commentary.',
  },

  // =====================================
  // 2. Regulators (7)
  // =====================================
  {
    name: 'Securities and Exchange Commission',
    code: 'SEC',
    type: SourceType.REGULATOR,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.sec.gov',
    feedUrl: 'https://www.sec.gov/rss/news/press.xml',
    apiUrl: 'https://data.sec.gov',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 120,
    status: 'active',
    description: 'US securities regulator — enforcement actions, rule changes, EDGAR filings.',
  },
  {
    name: 'Commodity Futures Trading Commission',
    code: 'CFTC',
    type: SourceType.REGULATOR,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.cftc.gov',
    feedUrl: 'https://www.cftc.gov/rss/pressroom/pressreleases.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'US derivatives regulator — Commitments of Traders, enforcement, rulemaking.',
  },
  {
    name: 'Financial Conduct Authority',
    code: 'FCA',
    type: SourceType.REGULATOR,
    country: 'GB',
    jurisdiction: 'United Kingdom',
    trustTier: 1,
    websiteUrl: 'https://www.fca.org.uk',
    feedUrl: 'https://www.fca.org.uk/news/rss/news-feed.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'UK financial regulator — conduct rules, supervision, enforcement.',
  },
  {
    name: 'BaFin',
    code: 'BAFIN',
    type: SourceType.REGULATOR,
    country: 'DE',
    jurisdiction: 'Germany',
    trustTier: 1,
    websiteUrl: 'https://www.bafin.de',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'German financial supervisor — banking, insurance, securities supervision.',
  },
  {
    name: 'Autorité des marchés financiers',
    code: 'AMF',
    type: SourceType.REGULATOR,
    country: 'FR',
    jurisdiction: 'France',
    trustTier: 1,
    websiteUrl: 'https://www.amf-france.org',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'French financial regulator — markets, savings, investment.',
  },
  {
    name: 'Securities and Futures Commission',
    code: 'SFC',
    type: SourceType.REGULATOR,
    country: 'HK',
    jurisdiction: 'Hong Kong SAR',
    trustTier: 1,
    websiteUrl: 'https://www.sfc.hk',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Hong Kong securities regulator — markets, intermediaries, products.',
  },
  {
    name: 'European Securities and Markets Authority',
    code: 'ESMA',
    type: SourceType.REGULATOR,
    country: 'EU',
    jurisdiction: 'European Union',
    trustTier: 1,
    websiteUrl: 'https://www.esma.europa.eu',
    feedUrl: 'https://www.esma.europa.eu/rss.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'EU securities markets supervisor — convergence, supervision, direct supervision.',
  },

  // =====================================
  // 3. Exchanges (5)
  // =====================================
  {
    name: 'New York Stock Exchange',
    code: 'NYSE',
    type: SourceType.EXCHANGE,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.nyse.com',
    feedUrl: 'https://www.nyse.com/rss/feeds/press-releases.xml',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'US primary equity exchange — listings, regulatory communications, market notices.',
  },
  {
    name: 'NASDAQ',
    code: 'NASDAQ',
    type: SourceType.EXCHANGE,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.nasdaq.com',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'US electronic exchange — listings, halts, market notices.',
  },
  {
    name: 'London Stock Exchange',
    code: 'LSE',
    type: SourceType.EXCHANGE,
    country: 'GB',
    jurisdiction: 'United Kingdom',
    trustTier: 1,
    websiteUrl: 'https://www.londonstockexchange.com',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'UK primary exchange — regulatory news service (RNS), market notices.',
  },
  {
    name: 'Eurex',
    code: 'EUREX',
    type: SourceType.EXCHANGE,
    country: 'EU',
    jurisdiction: 'European Union',
    trustTier: 1,
    websiteUrl: 'https://www.eurex.com',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'European derivatives exchange — contract specifications, circulars.',
  },
  {
    name: 'Tokyo Stock Exchange',
    code: 'TSE',
    type: SourceType.EXCHANGE,
    country: 'JP',
    jurisdiction: 'Japan',
    trustTier: 1,
    websiteUrl: 'https://www.jpx.co.jp',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Japan primary exchange — listings, trading halts, regulatory disclosures.',
  },

  // =====================================
  // 4. Statistical Agencies (5)
  // =====================================
  {
    name: 'Bureau of Labor Statistics',
    code: 'BLS',
    type: SourceType.STATISTICS,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.bls.gov',
    feedUrl: 'https://www.bls.gov/feed/release.rss',
    apiUrl: 'https://api.bls.gov/publicAPI/v2/timeseries/data/',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 60,
    status: 'active',
    description: 'US labor statistics — CPI, PPI, employment situation, JOLTS, ECI.',
  },
  {
    name: 'Bureau of Economic Analysis',
    code: 'BEA',
    type: SourceType.STATISTICS,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://www.bea.gov',
    apiUrl: 'https://apps.bea.gov/api/data/',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 60,
    status: 'active',
    description: 'US economic statistics — GDP, personal income, trade, industry accounts.',
  },
  {
    name: 'Eurostat',
    code: 'EUROSTAT',
    type: SourceType.STATISTICS,
    country: 'EU',
    jurisdiction: 'European Union',
    trustTier: 1,
    websiteUrl: 'https://ec.europa.eu/eurostat',
    apiUrl: 'https://ec.europa.eu/eurostat/api/dissemination',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'EU statistics office — macroeconomic, sectoral, regional statistics.',
  },
  {
    name: 'Office for National Statistics',
    code: 'ONS',
    type: SourceType.STATISTICS,
    country: 'GB',
    jurisdiction: 'United Kingdom',
    trustTier: 1,
    websiteUrl: 'https://www.ons.gov.uk',
    apiUrl: 'https://api.ons.gov.uk',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'UK statistics authority — CPI, GDP, labour market, trade.',
  },
  {
    name: 'Statistics Canada',
    code: 'STATCAN',
    type: SourceType.STATISTICS,
    country: 'CA',
    jurisdiction: 'Canada',
    trustTier: 1,
    websiteUrl: 'https://www.statcan.gc.ca',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Canada national statistics — CPI, GDP, labour force, trade.',
  },

  // =====================================
  // 5. Government Bodies (4)
  // =====================================
  {
    name: 'US Department of the Treasury',
    code: 'TREAS',
    type: SourceType.GOVERNMENT,
    country: 'US',
    jurisdiction: 'United States',
    trustTier: 1,
    websiteUrl: 'https://home.treasury.gov',
    feedUrl: 'https://home.treasury.gov/rss/press-releases',
    apiUrl: 'https://api.fiscaldata.treasury.gov/services/api/fiscal_service',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 300,
    status: 'active',
    description: 'US Treasury — fiscal policy, sanctions (OFAC), Treasury International Capital (TIC) data.',
  },
  {
    name: 'HM Treasury',
    code: 'HMT',
    type: SourceType.GOVERNMENT,
    country: 'GB',
    jurisdiction: 'United Kingdom',
    trustTier: 1,
    websiteUrl: 'https://www.gov.uk/government/organisations/hm-treasury',
    feedUrl: 'https://www.gov.uk/government/organisations/hm-treasury.atom',
    ingestionPattern: 'scheduled_polling',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'UK Treasury — fiscal policy, Budget, public finances.',
  },
  {
    name: 'Bundesministerium der Finanzen',
    code: 'BMF',
    type: SourceType.GOVERNMENT,
    country: 'DE',
    jurisdiction: 'Germany',
    trustTier: 1,
    websiteUrl: 'https://www.bundesfinanzministerium.de',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'German Federal Ministry of Finance — fiscal policy, tax, budget.',
  },
  {
    name: 'Ministry of Finance Japan',
    code: 'MOF',
    type: SourceType.GOVERNMENT,
    country: 'JP',
    jurisdiction: 'Japan',
    trustTier: 1,
    websiteUrl: 'https://www.mof.go.jp',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'Japan Ministry of Finance — fiscal policy, trade statistics, JGB auctions.',
  },

  // =====================================
  // 6. International Bodies (5)
  // =====================================
  {
    name: 'International Monetary Fund',
    code: 'IMF',
    type: SourceType.INTERNATIONAL_ORG,
    country: 'multinational',
    jurisdiction: 'International (Washington DC)',
    trustTier: 1,
    websiteUrl: 'https://www.imf.org',
    apiUrl: 'https://www.imf.org/external/datamapper/api/v1',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'IMF — World Economic Outlook, Article IV consultations, GFSR, GCR.',
  },
  {
    name: 'World Bank',
    code: 'WBG',
    type: SourceType.INTERNATIONAL_ORG,
    country: 'multinational',
    jurisdiction: 'International (Washington DC)',
    trustTier: 1,
    websiteUrl: 'https://www.worldbank.org',
    apiUrl: 'https://api.worldbank.org/v2',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'World Bank Group — World Development Indicators, global economic prospects.',
  },
  {
    name: 'Organisation for Economic Co-operation and Development',
    code: 'OECD',
    type: SourceType.INTERNATIONAL_ORG,
    country: 'multinational',
    jurisdiction: 'International (Paris)',
    trustTier: 1,
    websiteUrl: 'https://www.oecd.org',
    apiUrl: 'https://stats.oecd.org/SDMX-JSON/data',
    ingestionPattern: 'direct_api',
    pollingIntervalSec: 600,
    status: 'active',
    description: 'OECD — Economic Outlook, leading indicators, country surveys.',
  },
  {
    name: 'World Trade Organization',
    code: 'WTO',
    type: SourceType.INTERNATIONAL_ORG,
    country: 'multinational',
    jurisdiction: 'International (Geneva)',
    trustTier: 1,
    websiteUrl: 'https://www.wto.org',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 1800,
    status: 'active',
    description: 'WTO — trade policy reviews, World Trade Report, dispute settlements.',
  },
  {
    name: 'Financial Action Task Force',
    code: 'FATF',
    type: SourceType.INTERNATIONAL_ORG,
    country: 'multinational',
    jurisdiction: 'International (Paris)',
    trustTier: 1,
    websiteUrl: 'https://www.fatf-gafi.org',
    ingestionPattern: 'document_monitoring',
    pollingIntervalSec: 1800,
    status: 'active',
    description: 'FATF — AML/CFT standards, mutual evaluations, black/grey list updates.',
  },
];
