// ─── Geopolitical Risks i18n Translations ──────────────────────
// Supports: ar, en, fr, tr, es

export type GeoLocale = 'ar' | 'en' | 'fr' | 'tr' | 'es';

export const geoTranslations: Record<string, Record<GeoLocale, string>> = {
  // ─── Dashboard ──────────────────────────────────────────────
  'dashboard.title': {
    ar: 'المخاطر الجيوسياسية',
    en: 'Geopolitical Risks',
    fr: 'Risques Géopolitiques',
    tr: 'Jeopolitik Riskler',
    es: 'Riesgos Geopolíticos',
  },
  'dashboard.description': {
    ar: 'رصد وتحليل المخاطر الجيوسياسية وتأثيرها على الأسواق المالية والاقتصاد العربي والعالمي',
    en: 'Monitoring and analysis of geopolitical risks and their impact on financial markets and the global economy',
    fr: "Suivi et analyse des risques géopolitiques et leur impact sur les marchés financiers et l'économie mondiale",
    tr: 'Jeopolitik risklerin izlenmesi ve analizi ile finansal piyasalar ve küresel ekonomi üzerindeki etkileri',
    es: 'Seguimiento y análisis de riesgos geopolíticos y su impacto en los mercados financieros y la economía global',
  },
  'dashboard.realtimeBadge': {
    ar: 'بيانات حقيقية — البنك الدولي + GDELT + AI-GPR',
    en: 'Real data — World Bank + GDELT + AI-GPR',
    fr: 'Données réelles — Banque Mondiale + GDELT + AI-GPR',
    tr: 'Gerçek veriler — Dünya Bankası + GDELT + AI-GPR',
    es: 'Datos reales — Banco Mundial + GDELT + AI-GPR',
  },
  'dashboard.interactiveMap': {
    ar: 'الخريطة التفاعلية',
    en: 'Interactive Map',
    fr: 'Carte Interactive',
    tr: 'İnteraktif Harita',
    es: 'Mapa Interactivo',
  },
  'dashboard.scenarios': {
    ar: 'السيناريوهات',
    en: 'Scenarios',
    fr: 'Scénarios',
    tr: 'Senaryolar',
    es: 'Escenarios',
  },
  'dashboard.globalRiskLevel': {
    ar: 'مستوى الخطر العالمي',
    en: 'Global Risk Level',
    fr: 'Niveau de Risque Mondial',
    tr: 'Küresel Risk Seviyesi',
    es: 'Nivel de Riesgo Global',
  },
  'dashboard.riskMap': {
    ar: 'خريطة المخاطر الجيوسياسية',
    en: 'Geopolitical Risk Map',
    fr: 'Carte des Risques Géopolitiques',
    tr: 'Jeopolitik Risk Haritası',
    es: 'Mapa de Riesgos Geopolíticos',
  },
  'dashboard.loadingMap': {
    ar: 'جاري تحميل الخريطة...',
    en: 'Loading map...',
    fr: 'Chargement de la carte...',
    tr: 'Harita yükleniyor...',
    es: 'Cargando mapa...',
  },
  'dashboard.latestAnalyses': {
    ar: 'أحدث التحليلات',
    en: 'Latest Analyses',
    fr: 'Dernières Analyses',
    tr: 'Son Analizler',
    es: 'Últimos Análisis',
  },
  'dashboard.viewAll': {
    ar: 'عرض الكل',
    en: 'View All',
    fr: 'Voir Tout',
    tr: 'Tümünü Gör',
    es: 'Ver Todo',
  },
  'dashboard.noAnalyses': {
    ar: 'لا توجد تحليلات جيوسياسية حالياً',
    en: 'No geopolitical analyses available',
    fr: 'Aucune analyse géopolitique disponible',
    tr: 'Jeopolitik analiz mevcut değil',
    es: 'No hay análisis geopolíticos disponibles',
  },
  'dashboard.autoGenerated': {
    ar: 'يتم إنشاء التحليلات تلقائياً بناءً على البيانات العالمية',
    en: 'Analyses are automatically generated based on global data',
    fr: 'Les analyses sont générées automatiquement à partir des données mondiales',
    tr: 'Analizler küresel verilere dayalı olarak otomatik oluşturulur',
    es: 'Los análisis se generan automáticamente basándose en datos globales',
  },
  'dashboard.scenarioEngine': {
    ar: 'محرك السيناريوهات',
    en: 'Scenario Engine',
    fr: 'Moteur de Scénarios',
    tr: 'Senaryo Motoru',
    es: 'Motor de Escenarios',
  },
  'dashboard.scenarioDesc': {
    ar: 'استكشف السيناريوهات المحتملة وتأثيرها على الأسواق باستخدام نماذج المحاكاة الاحتمالية',
    en: 'Explore potential scenarios and their market impact using probabilistic simulation models',
    fr: "Explorez les scénarios potentiels et leur impact sur les marchés à l'aide de modèles de simulation probabilistes",
    tr: 'Olasılıksal simülasyon modellerini kullanarak olası senaryoları ve piyasa etkilerini keşfedin',
    es: 'Explore escenarios potenciales y su impacto en los mercados utilizando modelos de simulación probabilística',
  },
  'dashboard.runScenarios': {
    ar: 'تشغيل السيناريوهات',
    en: 'Run Scenarios',
    fr: 'Lancer les Scénarios',
    tr: 'Senaryoları Çalıştır',
    es: 'Ejecutar Escenarios',
  },
  'dashboard.topRiskCountries': {
    ar: 'الدول الأكثر خطورة',
    en: 'Highest Risk Countries',
    fr: 'Pays les Plus Risqués',
    tr: 'En Yüksek Riskli Ülkeler',
    es: 'Países de Mayor Riesgo',
  },
  'dashboard.tradeRoutes': {
    ar: 'طرق التجارة',
    en: 'Trade Routes',
    fr: 'Routes Commerciales',
    tr: 'Ticaret Yolları',
    es: 'Rutas Comerciales',
  },
  'dashboard.details': {
    ar: 'التفاصيل',
    en: 'Details',
    fr: 'Détails',
    tr: 'Detaylar',
    es: 'Detalles',
  },
  'dashboard.last7Days': {
    ar: 'آخر 7 أيام',
    en: 'Last 7 Days',
    fr: '7 Derniers Jours',
    tr: 'Son 7 Gün',
    es: 'Últimos 7 Días',
  },
  'dashboard.event': {
    ar: 'حدث',
    en: 'Events',
    fr: 'Événements',
    tr: 'Olay',
    es: 'Eventos',
  },
  'dashboard.country': {
    ar: 'دولة',
    en: 'Countries',
    fr: 'Pays',
    tr: 'Ülke',
    es: 'Países',
  },
  'dashboard.noDisruptions': {
    ar: 'لا توجد اضطرابات حالياً في طرق التجارة',
    en: 'No current disruptions in trade routes',
    fr: 'Aucune perturbation actuelle des routes commerciales',
    tr: 'Ticaret yollarında şu anda bir kesinti yok',
    es: 'Sin interrupciones actuales en las rutas comerciales',
  },
  'dashboard.riskDashboard': {
    ar: 'لوحة المخاطر',
    en: 'Risk Dashboard',
    fr: 'Tableau de Bord des Risques',
    tr: 'Risk Paneli',
    es: 'Panel de Riesgos',
  },
  'dashboard.scenariosTag': {
    ar: 'سيناريوهات',
    en: 'Scenarios',
    fr: 'Scénarios',
    tr: 'Senaryolar',
    es: 'Escenarios',
  },

  // ─── Navigation Cards ───────────────────────────────────────
  'nav.riskMap': { ar: 'خريطة المخاطر', en: 'Risk Map', fr: 'Carte des Risques', tr: 'Risk Haritası', es: 'Mapa de Riesgos' },
  'nav.heatmap': { ar: 'خريطة الحرارة', en: 'Heatmap', fr: 'Carte de Chaleur', tr: 'Isı Haritası', es: 'Mapa de Calor' },
  'nav.tradeRoutes': { ar: 'طرق التجارة', en: 'Trade Routes', fr: 'Routes Commerciales', tr: 'Ticaret Yolları', es: 'Rutas Comerciales' },
  'nav.reports': { ar: 'التقارير', en: 'Reports', fr: 'Rapports', tr: 'Raporlar', es: 'Informes' },

  // ─── Risk Categories ────────────────────────────────────────
  'category.conflict': { ar: 'نزاعات', en: 'Conflict', fr: 'Conflits', tr: 'Çatışmalar', es: 'Conflictos' },
  'category.trade': { ar: 'تجارة', en: 'Trade', fr: 'Commerce', tr: 'Ticaret', es: 'Comercio' },
  'category.energy': { ar: 'طاقة', en: 'Energy', fr: 'Énergie', tr: 'Enerji', es: 'Energía' },
  'category.political': { ar: 'سياسي', en: 'Political', fr: 'Politique', tr: 'Siyasi', es: 'Político' },
  'category.cyber': { ar: 'سيبراني', en: 'Cyber', fr: 'Cyber', tr: 'Siber', es: 'Cibernético' },
  'category.sanctions': { ar: 'عقوبات', en: 'Sanctions', fr: 'Sanctions', tr: 'Yaptırımlar', es: 'Sanciones' },
  'category.all': { ar: 'الكل', en: 'All', fr: 'Tous', tr: 'Tümü', es: 'Todos' },
  'category.climate': { ar: 'مناخي', en: 'Climate', fr: 'Climatique', tr: 'İklim', es: 'Climático' },

  // ─── Time ───────────────────────────────────────────────────
  'time.now': { ar: 'الآن', en: 'Now', fr: 'Maintenant', tr: 'Şimdi', es: 'Ahora' },
  'time.minute': { ar: 'دقيقة', en: 'min', fr: 'min', tr: 'dk', es: 'min' },
  'time.hour': { ar: 'ساعة', en: 'hours', fr: 'heures', tr: 'saat', es: 'horas' },
  'time.day': { ar: 'يوم', en: 'days', fr: 'jours', tr: 'gün', es: 'días' },
  'time.month': { ar: 'شهر', en: 'months', fr: 'mois', tr: 'ay', es: 'meses' },

  // ─── Trade Routes Status ────────────────────────────────────
  'status.stable': { ar: 'مستقر', en: 'Stable', fr: 'Stable', tr: 'Stabil', es: 'Estable' },
  'status.elevated': { ar: 'مرتفع', en: 'Elevated', fr: 'Élevé', tr: 'Yüksek', es: 'Elevado' },
  'status.disrupted': { ar: 'متأثر', en: 'Disrupted', fr: 'Perturbé', tr: 'Etkilenmiş', es: 'Interrumpido' },
  'status.critical': { ar: 'حرج', en: 'Critical', fr: 'Critique', tr: 'Kritik', es: 'Crítico' },
  'status.normal': { ar: 'طبيعي', en: 'Normal', fr: 'Normal', tr: 'Normal', es: 'Normal' },
  'status.threatened': { ar: 'مهدد', en: 'Threatened', fr: 'Menacé', tr: 'Tehdit Altında', es: 'Amenazado' },
  'status.blocked': { ar: 'محظور', en: 'Blocked', fr: 'Bloqué', tr: 'Engelli', es: 'Bloqueado' },

  // ─── Map Page ───────────────────────────────────────────────
  'map.title': { ar: 'خريطة المخاطر التفاعلية', en: 'Interactive Risk Map', fr: 'Carte Interactive des Risques', tr: 'İnteraktif Risk Haritası', es: 'Mapa Interactivo de Riesgos' },
  'map.back': { ar: 'العودة', en: 'Back', fr: 'Retour', tr: 'Geri', es: 'Volver' },
  'map.country': { ar: 'دولة', en: 'countries', fr: 'pays', tr: 'ülke', es: 'países' },
  'map.event': { ar: 'حدث', en: 'events', fr: 'événements', tr: 'olay', es: 'eventos' },
  'map.riskLevel': { ar: 'مستوى الخطر', en: 'Risk Level', fr: 'Niveau de Risque', tr: 'Risk Seviyesi', es: 'Nivel de Riesgo' },
  'map.heatmapView': { ar: 'خريطة حرارية', en: 'Heatmap', fr: 'Carte de Chaleur', tr: 'Isı Haritası', es: 'Mapa de Calor' },
  'map.events': { ar: 'الأحداث', en: 'Events', fr: 'Événements', tr: 'Olaylar', es: 'Eventos' },
  'map.region': { ar: 'المنطقة', en: 'Region', fr: 'Région', tr: 'Bölge', es: 'Región' },
  'map.riskRanking': { ar: 'ترتيب المخاطر حسب الدولة', en: 'Risk Ranking by Country', fr: 'Classement des Risques par Pays', tr: 'Ülkeye Göre Risk Sıralaması', es: 'Ranking de Riesgos por País' },
  'map.eventSummary': { ar: 'ملخص الأحداث', en: 'Event Summary', fr: 'Résumé des Événements', tr: 'Olay Özeti', es: 'Resumen de Eventos' },
  'map.all': { ar: 'الكل', en: 'All', fr: 'Tout', tr: 'Tümü', es: 'Todo' },
  'map.middleEast': { ar: 'الشرق الأوسط', en: 'Middle East', fr: 'Moyen-Orient', tr: 'Orta Doğu', es: 'Medio Oriente' },
  'map.africa': { ar: 'أفريقيا', en: 'Africa', fr: 'Afrique', tr: 'Afrika', es: 'África' },
  'map.europe': { ar: 'أوروبا', en: 'Europe', fr: 'Europe', tr: 'Avrupa', es: 'Europa' },
  'map.eastAsia': { ar: 'شرق آسيا', en: 'East Asia', fr: "Asie de l'Est", tr: 'Doğu Asya', es: 'Asia Oriental' },
  'map.americas': { ar: 'الأمريكتان', en: 'Americas', fr: 'Amériques', tr: 'Amerika', es: 'Américas' },

  // ─── Event Types ────────────────────────────────────────────
  'event.battle': { ar: 'معارك', en: 'Battles', fr: 'Batailles', tr: 'Çatışmalar', es: 'Batallas' },
  'event.protest': { ar: 'احتجاجات', en: 'Protests', fr: 'Protestations', tr: 'Protestolar', es: 'Protestas' },
  'event.riot': { ar: 'شغب', en: 'Riots', fr: 'Émeutes', tr: 'Ayaklanmalar', es: 'Disturbios' },
  'event.violenceCivilians': { ar: 'عنف ضد مدنيين', en: 'Violence vs Civilians', fr: 'Violence contre les Civils', tr: 'Sivillere Şiddet', es: 'Violencia contra Civiles' },
  'event.strategicDev': { ar: 'تطورات استراتيجية', en: 'Strategic Developments', fr: 'Développements Stratégiques', tr: 'Stratejik Gelişmeler', es: 'Desarrollos Estratégicos' },
  'event.violenceCivShort': { ar: 'عنف مدني', en: 'Civ. Violence', fr: 'Violence civ.', tr: 'Sivil şiddet', es: 'Violencia civ.' },

  // ─── Reports Page ───────────────────────────────────────────
  'reports.title': { ar: 'تقارير المخاطر الجيوسياسية', en: 'Geopolitical Risk Reports', fr: 'Rapports sur les Risques Géopolitiques', tr: 'Jeopolitik Risk Raporları', es: 'Informes de Riesgos Geopolíticos' },
  'reports.description': { ar: 'جميع التحليلات والتقارير مع إمكانية البحث والتصفية حسب الفئة ومستوى الخطر', en: 'All analyses and reports with search and filtering by category and risk level', fr: 'Toutes les analyses et rapports avec recherche et filtrage par catégorie et niveau de risque', tr: 'Kategori ve risk seviyesine göre arama ve filtreleme ile tüm analizler ve raporlar', es: 'Todos los análisis e informes con búsqueda y filtrado por categoría y nivel de riesgo' },
  'reports.searchPlaceholder': { ar: 'ابحث في التقارير...', en: 'Search reports...', fr: 'Rechercher des rapports...', tr: 'Raporlarda ara...', es: 'Buscar informes...' },
  'reports.category': { ar: 'الفئة:', en: 'Category:', fr: 'Catégorie:', tr: 'Kategori:', es: 'Categoría:' },
  'reports.level': { ar: 'المستوى:', en: 'Level:', fr: 'Niveau:', tr: 'Seviye:', es: 'Nivel:' },
  'reports.showing': { ar: 'عرض', en: 'Showing', fr: 'Affichage de', tr: 'Gösterilen', es: 'Mostrando' },
  'reports.of': { ar: 'من', en: 'of', fr: 'sur', tr: '/', es: 'de' },
  'reports.report': { ar: 'تقرير', en: 'reports', fr: 'rapports', tr: 'rapor', es: 'informes' },
  'reports.noResults': { ar: 'لا توجد تقارير مطابقة للفلاتر المحددة', en: 'No reports matching the selected filters', fr: 'Aucun rapport ne correspond aux filtres sélectionnés', tr: 'Seçili filtrelerle eşleşen rapor yok', es: 'No hay informes que coincidan con los filtros seleccionados' },
  'reports.tryFilters': { ar: 'حاول تغيير معايير البحث أو الفلاتر', en: 'Try changing search criteria or filters', fr: 'Essayez de modifier les critères de recherche ou les filtres', tr: 'Arama kriterlerini veya filtreleri değiştirmeyi deneyin', es: 'Intente cambiar los criterios de búsqueda o filtros' },

  // ─── Risk Levels ────────────────────────────────────────────
  'risk.low': { ar: 'منخفض', en: 'Low', fr: 'Faible', tr: 'Düşük', es: 'Bajo' },
  'risk.moderate': { ar: 'معتدل', en: 'Moderate', fr: 'Modéré', tr: 'Orta', es: 'Moderado' },
  'risk.elevated': { ar: 'مرتفع', en: 'Elevated', fr: 'Élevé', tr: 'Yüksek', es: 'Elevado' },
  'risk.high': { ar: 'عالٍ', en: 'High', fr: 'Élevé', tr: 'Çok Yüksek', es: 'Alto' },
  'risk.all': { ar: 'الكل', en: 'All', fr: 'Tous', tr: 'Tümü', es: 'Todos' },
  'risk.severe': { ar: 'شديد', en: 'Severe', fr: 'Sévère', tr: 'Şiddetli', es: 'Severo' },

  // ─── Scenarios Page ─────────────────────────────────────────
  'scenarios.title': { ar: 'محرك السيناريوهات', en: 'Scenario Engine', fr: 'Moteur de Scénarios', tr: 'Senaryo Motoru', es: 'Motor de Escenarios' },
  'scenarios.description': { ar: 'استكشف السيناريوهات المحتملة للأزمات الجيوسياسية وتأثيرها المحتمل على الأسواق المالية', en: 'Explore potential scenarios for geopolitical crises and their possible impact on financial markets', fr: 'Explorez les scénarios potentiels de crises géopolitiques et leur impact possible sur les marchés financiers', tr: 'Jeopolitik krizlerin olası senaryolarını ve finansal piyasalar üzerindeki olası etkilerini keşfedin', es: 'Explore escenarios potenciales de crisis geopolíticas y su posible impacto en los mercados financieros' },
  'scenarios.available': { ar: 'السيناريوهات المتاحة', en: 'Available Scenarios', fr: 'Scénarios Disponibles', tr: 'Mevcut Senaryolar', es: 'Escenarios Disponibles' },
  'scenarios.noScenarios': { ar: 'لا توجد سيناريوهات متاحة حالياً', en: 'No scenarios currently available', fr: 'Aucun scénario disponible actuellement', tr: 'Şu anda mevcut senaryo yok', es: 'No hay escenarios disponibles actualmente' },
  'scenarios.autoGenerated': { ar: 'يتم إنشاء السيناريوهات تلقائياً بناءً على تحليل البيانات الجيوسياسية', en: 'Scenarios are automatically generated based on geopolitical data analysis', fr: "Les scénarios sont générés automatiquement à partir de l'analyse des données géopolitiques", tr: 'Senaryolar jeopolitik veri analizine dayalı olarak otomatik olarak oluşturulur', es: 'Los escenarios se generan automáticamente basándose en el análisis de datos geopolíticos' },
  'scenarios.baseCase': { ar: 'السيناريو الأساسي', en: 'Base Case', fr: 'Scénario de Base', tr: 'Temel Senaryo', es: 'Caso Base' },
  'scenarios.adverseCase': { ar: 'سيناريو سلبي', en: 'Adverse Case', fr: 'Scénario Défavorable', tr: 'Olumsuz Senaryo', es: 'Caso Adverso' },
  'scenarios.severeCase': { ar: 'سيناريو حاد', en: 'Severe Case', fr: 'Scénario Sévère', tr: 'Şiddetli Senaryo', es: 'Caso Severo' },
  'scenarios.aboutMethodology': { ar: 'عن منهجية السيناريوهات', en: 'About Scenario Methodology', fr: 'À Propos de la Méthodologie des Scénarios', tr: 'Senaryo Metodolojisi Hakkında', es: 'Sobre la Metodología de Escenarios' },
  'scenarios.baseDesc': { ar: 'يمثل المسار الأكثر احتمالاً بناءً على البيانات الحالية والاتجاهات التاريخية. يعكس الاستمرارية مع تعديلات طفيفة.', en: 'Represents the most likely path based on current data and historical trends. Reflects continuity with minor adjustments.', fr: "Représente le parcours le plus probable basé sur les données actuelles et les tendances historiques. Reflète la continuité avec des ajustements mineurs.", tr: 'Mevcut veriler ve tarihsel eğilimlere dayalı en olası yolu temsil eder. Küçük ayarlamalarla sürekliliği yansıtır.', es: 'Representa el camino más probable basado en datos actuales y tendencias históricas. Refleja continuidad con ajustes menores.' },
  'scenarios.adverseDesc': { ar: 'يأخذ في الاعتبار تصعيد التوترات أو تفاقم الأوضاع مع تأثير متوسط إلى مرتفع على الأسواق والاقتصاد.', en: 'Considers escalation of tensions or worsening conditions with medium to high impact on markets and the economy.', fr: "Prend en compte l'escalade des tensions ou la détérioration des conditions avec un impact moyen à élevé sur les marchés et l'économie.", tr: 'Gerilimlerin tırmanmasını veya koşulların kötüleşmesini piyasalar ve ekonomi üzerinde orta ila yüksek etki ile dikkate alır.', es: 'Considera la escalada de tensiones o el empeoramiento de las condiciones con impacto medio a alto en los mercados y la economía.' },
  'scenarios.severeDesc': { ar: 'يحاكي أسوأ الحالات مع تأثير شديد على الأسواق العالمية، يشمل نماذج مونت كارلو لحساب الاحتمالات.', en: 'Simulates worst-case scenarios with severe impact on global markets, including Monte Carlo models for probability calculations.', fr: 'Simule les pires scénarios avec un impact sévère sur les marchés mondiaux, incluant des modèles de Monte Carlo pour les calculs de probabilité.', tr: 'Küresel piyasalar üzerinde şiddetli etki ile en kötü senaryoları simüle eder, olasılık hesaplamaları için Monte Carlo modellerini içerir.', es: 'Simula los peores escenarios con impacto severo en los mercados globales, incluyendo modelos de Monte Carlo para cálculos de probabilidad.' },
  'scenarios.methodologyNote': { ar: 'تعتمد السيناريوهات على نماذج محاكاة مونت كارلو مع آلاف التكرارات، وتستخدم بيانات من مؤشر AI-GPR للبنك الاحتياطي الفيدرالي، وقاعدة بيانات ACLED، ومؤشرات البنك الدولي، ونبرة GDELT الإعلامية. الاحتمالات المعروضة تقديرية ولا تشكل ضمانات.', en: 'Scenarios are based on Monte Carlo simulation models with thousands of iterations, using data from the Fed AI-GPR Index, ACLED database, World Bank indicators, and GDELT media tone. Probabilities shown are estimates and do not constitute guarantees.', fr: "Les scénarios sont basés sur des modèles de simulation Monte Carlo avec des milliers d'itérations, utilisant des données de l'indice AI-GPR de la Fed, la base de données ACLED, les indicateurs de la Banque Mondiale et le ton médiatique GDELT. Les probabilités affichées sont des estimations et ne constituent pas des garanties.", tr: 'Senaryolar, Fed AI-GPR İndeksi, ACLED veritabanı, Dünya Bankası göstergeleri ve GDELT medya tonu verilerini kullanan binlerce yinelemeli Monte Carlo simülasyon modellerine dayanmaktadır. Gösterilen olasılıklar tahminidir ve garanti niteliğinde değildir.', es: 'Los escenarios se basan en modelos de simulación de Monte Carlo con miles de iteraciones, utilizando datos del Índice AI-GPR de la Fed, la base de datos ACLED, indicadores del Banco Mundial y el tono mediático GDELT. Las probabilidades mostradas son estimaciones y no constituyen garantías.' },

  // ─── Trade Routes Page ──────────────────────────────────────
  'tradeRoutes.title': { ar: 'طرق التجارة العالمية', en: 'Global Trade Routes', fr: 'Routes Commerciales Mondiales', tr: 'Küresel Ticaret Yolları', es: 'Rutas Comerciales Globales' },
  'tradeRoutes.description': { ar: 'متابعة طرق التجارة العالمية وحالة الاضطرابات وتأثيرها على تدفقات الطاقة والسلع', en: 'Tracking global trade routes, disruption status, and their impact on energy and commodity flows', fr: "Suivi des routes commerciales mondiales, de l'état des perturbations et de leur impact sur les flux d'énergie et de marchandises", tr: 'Küresel ticaret yollarının, kesinti durumunun ve enerji ile emtia akışları üzerindeki etkilerinin izlenmesi', es: 'Seguimiento de rutas comerciales globales, estado de interrupciones y su impacto en los flujos de energía y materias primas' },
  'tradeRoutes.tradeRoute': { ar: 'طريق تجاري', en: 'Trade Routes', fr: 'Routes Commerciales', tr: 'Ticaret Yolu', es: 'Rutas Comerciales' },
  'tradeRoutes.disrupted': { ar: 'طريق متأثر', en: 'Disrupted', fr: 'Perturbé', tr: 'Etkilenmiş', es: 'Interrumpido' },
  'tradeRoutes.elevatedRisk': { ar: 'طريق مرتفع الخطر', en: 'Elevated Risk', fr: 'Risque Élevé', tr: 'Yüksek Riskli', es: 'Riesgo Elevado' },
  'tradeRoutes.stable': { ar: 'طريق مستقر', en: 'Stable', fr: 'Stable', tr: 'Stabil', es: 'Estable' },
  'tradeRoutes.tradeMap': { ar: 'خريطة طرق التجارة', en: 'Trade Routes Map', fr: 'Carte des Routes Commerciales', tr: 'Ticaret Yolları Haritası', es: 'Mapa de Rutas Comerciales' },
  'tradeRoutes.routeStatus': { ar: 'حالة الطرق التجارية', en: 'Trade Route Status', fr: 'État des Routes Commerciales', tr: 'Ticaret Yolu Durumu', es: 'Estado de Rutas Comerciales' },
  'tradeRoutes.oilFlows': { ar: 'تدفقات النفط العالمية', en: 'Global Oil Flows', fr: 'Flux Pétroliers Mondiaux', tr: 'Küresel Petrol Akışları', es: 'Flujos Petroleros Globales' },
  'tradeRoutes.type': { ar: 'النوع', en: 'Type', fr: 'Type', tr: 'Tür', es: 'Tipo' },
  'tradeRoutes.dailyVolume': { ar: 'الحجم اليومي', en: 'Daily Volume', fr: 'Volume Quotidien', tr: 'Günlük Hacim', es: 'Volumen Diario' },
  'tradeRoutes.borderingCountries': { ar: 'الدول المطلة', en: 'Bordering Countries', fr: 'Pays Frontaliers', tr: 'Sınır Ülkeler', es: 'Países Limítrofes' },
  'tradeRoutes.disruptionRisk': { ar: 'خطر الاضطراب', en: 'Disruption Risk', fr: 'Risque de Perturbation', tr: 'Kesinti Riski', es: 'Riesgo de Interrupción' },
  'tradeRoutes.noData': { ar: 'لا توجد بيانات طرق التجارة حالياً', en: 'No trade route data available', fr: 'Aucune donnée de route commerciale disponible', tr: 'Ticaret yolu verisi mevcut değil', es: 'No hay datos de rutas comerciales disponibles' },
  'tradeRoutes.oilFlowsDesc': { ar: 'نسبة النفط المنقول عبر كل مضيق من إجمالي النفط العالمي المنقول بحراً', en: 'Percentage of oil transported through each strait out of total global seaborne oil', fr: 'Pourcentage de pétrole transporté à travers chaque détroit sur le total du pétrole transporté par voie maritime', tr: 'Her boğazdan taşınan petrolün toplam deniz yoluyla taşınan küresel petrol oranı', es: 'Porcentaje de petróleo transportado a través de cada estrecho del total de petróleo marítimo global' },
  'tradeRoutes.disruptionImpact': { ar: 'تأثير الاضطرابات', en: 'Disruption Impact', fr: 'Impact des Perturbations', tr: 'Kesinti Etkisi', es: 'Impacto de Interrupciones' },
  'tradeRoutes.disruptionNote': { ar: 'إغلاق مضيق هرمز قد يرفع أسعار النفط بنسبة 20-40%، وإغلاق باب المندب يعطل حركة الشحن عبر قناة السويس', en: 'Closing the Strait of Hormuz could raise oil prices by 20-40%, and closing Bab el-Mandeb disrupts shipping through the Suez Canal', fr: "La fermeture du détroit d'Ormuz pourrait augmenter les prix du pétrole de 20-40%, et la fermeture de Bab el-Mandeb perturbe le transport maritime par le canal de Suez", tr: 'Hürmüz Boğazı\'nın kapatılması petrol fiyatlarını %20-40 artırabilir ve Babülmendeb\'nin kapatılması Süveyş Kanalı üzerinden deniz taşımacılığını aksatır', es: 'El cierre del Estrecho de Ormuz podría aumentar los precios del petróleo en un 20-40%, y el cierre de Bab el-Mandeb interrumpe el envío por el Canal de Suez' },
  'tradeRoutes.tradeVolume': { ar: 'حجم التجارة', en: 'Trade Volume', fr: 'Volume Commercial', tr: 'Ticaret Hacmi', es: 'Volumen Comercial' },
  'tradeRoutes.ofGlobalTrade': { ar: 'من التجارة العالمية', en: 'of global trade', fr: 'du commerce mondial', tr: 'küresel ticaretin', es: 'del comercio global' },
  'tradeRoutes.chokepoints': { ar: 'نقاط الاختناق', en: 'Chokepoints', fr: 'Goulets d\'Étranglement', tr: 'Darboğazlar', es: 'Puntos de Estrangulamiento' },
  'tradeRoutes.route': { ar: 'مسار', en: 'Route', fr: 'Route', tr: 'Rota', es: 'Ruta' },
  'tradeRoutes.other': { ar: 'أخرى', en: 'Other', fr: 'Autres', tr: 'Diğer', es: 'Otros' },

  // ─── Heatmap Page ───────────────────────────────────────────
  'heatmap.title': { ar: 'خريطة حرارة الأحداث', en: 'Event Heatmap', fr: 'Carte de Chaleur des Événements', tr: 'Olay Isı Haritası', es: 'Mapa de Calor de Eventos' },
  'heatmap.description': { ar: 'خريطة حرارة تفاعلية للأحداث الجيوسياسية مع فلاتر حسب النوع والدولة والتاريخ', en: 'Interactive heatmap of geopolitical events with filters by type, country, and date', fr: 'Carte de chaleur interactive des événements géopolitiques avec filtres par type, pays et date', tr: 'Tür, ülke ve tarihe göre filtrelerle jeopolitik olayların interaktif ısı haritası', es: 'Mapa de calor interactivo de eventos geopolíticos con filtros por tipo, país y fecha' },
  'heatmap.type': { ar: 'النوع:', en: 'Type:', fr: 'Type:', tr: 'Tür:', es: 'Tipo:' },
  'heatmap.country': { ar: 'الدولة:', en: 'Country:', fr: 'Pays:', tr: 'Ülke:', es: 'País:' },
  'heatmap.allCountries': { ar: 'جميع الدول', en: 'All Countries', fr: 'Tous les Pays', tr: 'Tüm Ülkeler', es: 'Todos los Países' },
  'heatmap.shownEvents': { ar: 'الأحداث المعروضة:', en: 'Displayed Events:', fr: 'Événements Affichés:', tr: 'Gösterilen Olaylar:', es: 'Eventos Mostrados:' },
  'heatmap.summary': { ar: 'ملخص الأحداث', en: 'Event Summary', fr: 'Résumé des Événements', tr: 'Olay Özeti', es: 'Resumen de Eventos' },
  'heatmap.totalEvents': { ar: 'إجمالي الأحداث', en: 'Total Events', fr: 'Total Événements', tr: 'Toplam Olay', es: 'Total Eventos' },
  'heatmap.totalFatalities': { ar: 'إجمالي الوفيات', en: 'Total Fatalities', fr: 'Total Décès', tr: 'Toplam Ölüler', es: 'Total Fallecidos' },
  'heatmap.affectedCountries': { ar: 'الدول المتأثرة', en: 'Affected Countries', fr: 'Pays Affectés', tr: 'Etkilenen Ülkeler', es: 'Países Afectados' },
  'heatmap.typeBreakdown': { ar: 'توزيع حسب النوع', en: 'Distribution by Type', fr: 'Distribution par Type', tr: 'Türe Göre Dağılım', es: 'Distribución por Tipo' },
  'heatmap.topCountries': { ar: 'أكثر الدول تأثراً', en: 'Most Affected Countries', fr: 'Pays les Plus Affectés', tr: 'En Çok Etkilenen Ülkeler', es: 'Países Más Afectados' },
  'heatmap.recentEvents': { ar: 'أحدث الأحداث', en: 'Recent Events', fr: 'Événements Récents', tr: 'Son Olaylar', es: 'Eventos Recientes' },
  'heatmap.date': { ar: 'التاريخ', en: 'Date', fr: 'Date', tr: 'Tarih', es: 'Fecha' },
  'heatmap.typeCol': { ar: 'النوع', en: 'Type', fr: 'Type', tr: 'Tür', es: 'Tipo' },
  'heatmap.countryCol': { ar: 'الدولة', en: 'Country', fr: 'Pays', tr: 'Ülke', es: 'País' },
  'heatmap.fatalitiesCol': { ar: 'الوفيات', en: 'Fatalities', fr: 'Décès', tr: 'Ölüler', es: 'Fallecidos' },
  'heatmap.detailsCol': { ar: 'التفاصيل', en: 'Details', fr: 'Détails', tr: 'Detaylar', es: 'Detalles' },
  'heatmap.noEvents': { ar: 'لا توجد أحداث كافية لعرض خريطة الحرارة', en: 'Not enough events to display the heatmap', fr: "Pas assez d'événements pour afficher la carte de chaleur", tr: 'Isı haritasını görüntülemek için yeterli olay yok', es: 'No hay suficientes eventos para mostrar el mapa de calor' },
  'heatmap.openMap': { ar: 'فتح الخريطة التفاعلية', en: 'Open Interactive Map', fr: 'Ouvrir la Carte Interactive', tr: 'İnteraktif Haritayı Aç', es: 'Abrir Mapa Interactivo' },
  'heatmap.loadingHeatmap': { ar: 'جاري تحميل خريطة الحرارة...', en: 'Loading heatmap...', fr: 'Chargement de la carte de chaleur...', tr: 'Isı haritası yükleniyor...', es: 'Cargando mapa de calor...' },

  // ─── Dashboard — Advanced Analytics ──────────────────────
  'dashboard.advancedAnalytics': { ar: 'ميزات تحليلية متقدمة', en: 'Advanced Analytics', fr: 'Analyses Avancées', tr: 'Gelişmiş Analitikler', es: 'Análisis Avanzados' },
  'dashboard.advancedAnalyticsDesc': { ar: 'محركات ذكاء اصطناعي ونماذج رياضية متقدمة', en: 'AI-powered engines & advanced mathematical models', fr: 'Moteurs IA et modèles mathématiques avancés', tr: 'Yapay zeka motorları ve gelişmiş matematiksel modeller', es: 'Motores de IA y modelos matemáticos avanzados' },
  'dashboard.confidenceIntervals': { ar: 'فترات الثقة — أعلى أولوية', en: 'Confidence Intervals — Top Priority', fr: 'Intervalles de Confiance — Priorité Maximale', tr: 'Güven Aralıkları — En Yüksek Öncelik', es: 'Intervalos de Confianza — Máxima Prioridad' },
  'dashboard.globalCompositeScore': { ar: 'الدرجة المركبة العالمية', en: 'Global Composite Score', fr: 'Score Composite Mondial', tr: 'Küresel Bileşik Skor', es: 'Puntuación Compuesta Global' },
  'dashboard.ciDisclaimer': { ar: 'جميع الدرجات معروضة مع فترات ثقة 95% لتجنب الإيحاء الزائف بالدقة. محاكاة Monte Carlo تُنتج التوزيعات.', en: 'All scores displayed with 95% confidence intervals to avoid false precision. Monte Carlo simulation produces the distributions.', fr: 'Tous les scores sont affichés avec des intervalles de confiance à 95% pour éviter la fausse précision. La simulation Monte Carlo produit les distributions.', tr: 'Tüm skorlar yanlış kesinlikten kaçınmak için %95 güven aralığıyla gösterilir. Monte Carlo simülasyonu dağılımları üretir.', es: 'Todas las puntuaciones se muestran con intervalos de confianza del 95% para evitar una falsa precisión. La simulación Monte Carlo produce las distribuciones.' },

  // ─── Map — RiskMap layer toggles & errors ──────────────
  'map.countryRisk': { ar: 'مخاطر الدول', en: 'Country Risk', fr: 'Risque Pays', tr: 'Ülke Riski', es: 'Riesgo País' },
  'map.eventsLayer': { ar: 'الأحداث', en: 'Events', fr: 'Événements', tr: 'Olaylar', es: 'Eventos' },
  'map.tradeRoutesLayer': { ar: 'طرق التجارة', en: 'Trade Routes', fr: 'Routes Commerciales', tr: 'Ticaret Yolları', es: 'Rutas Comerciales' },
  'map.webglError': { ar: 'متصفحك لا يدعم WebGL المطلوب للخريطة', en: 'Your browser does not support WebGL required for maps', fr: 'Votre navigateur ne prend pas en charge WebGL requis pour les cartes', tr: 'Haritalar için gereken WebGL tarayıcınız tarafından desteklenmiyor', es: 'Su navegador no es compatible con WebGL necesario para los mapas' },
  'map.loadingError': { ar: 'حدث خطأ في تحميل الخريطة', en: 'Map loading error occurred', fr: 'Une erreur de chargement de la carte est survenue', tr: 'Harita yükleme hatası oluştu', es: 'Error al cargar el mapa' },
  'map.dataError': { ar: 'فشل تحميل بيانات الخريطة', en: 'Failed to load map data', fr: 'Échec du chargement des données de la carte', tr: 'Harita verileri yüklenemedi', es: 'Error al cargar los datos del mapa' },
  'map.initError': { ar: 'فشل تهيئة الخريطة', en: 'Failed to initialize map', fr: 'Échec de l\'initialisation de la carte', tr: 'Harita başlatılamadı', es: 'Error al inicializar el mapa' },
  'map.retry': { ar: 'إعادة المحاولة', en: 'Retry', fr: 'Réessayer', tr: 'Tekrar Dene', es: 'Reintentar' },
  'map.risk': { ar: 'مخاطر', en: 'Risk', fr: 'Risque', tr: 'Risk', es: 'Riesgo' },
  'map.heat': { ar: 'حراري', en: 'Heat', fr: 'Chaleur', tr: 'Isı', es: 'Calor' },
  'map.layers': { ar: 'الطبقات', en: 'Layers', fr: 'Couches', tr: 'Katmanlar', es: 'Capas' },
  'map.riskScale': { ar: 'مقياس المخاطر', en: 'Risk Scale', fr: 'Échelle de Risque', tr: 'Risk Ölçeği', es: 'Escala de Riesgo' },
  'map.low': { ar: 'منخفض', en: 'Low', fr: 'Faible', tr: 'Düşük', es: 'Bajo' },
  'map.moderate': { ar: 'معتدل', en: 'Mod', fr: 'Modéré', tr: 'Orta', es: 'Mod' },
  'map.elevated': { ar: 'مرتفع', en: 'Elev', fr: 'Élevé', tr: 'Yüksek', es: 'Elev' },
  'map.high': { ar: 'عالٍ', en: 'High', fr: 'Élevé', tr: 'Çok Ykşk', es: 'Alto' },
  'map.critical': { ar: 'حرج', en: 'Crit', fr: 'Critique', tr: 'Kritik', es: 'Crít' },

  // ─── HeatmapLayer legend ──────────────────────────────────
  'heatmap.eventDensity': { ar: 'كثافة الأحداث', en: 'Event Density', fr: 'Densité des Événements', tr: 'Olay Yoğunluğu', es: 'Densidad de Eventos' },
  'heatmap.lowDensity': { ar: 'منخفض', en: 'Low', fr: 'Faible', tr: 'Düşük', es: 'Bajo' },
  'heatmap.medDensity': { ar: 'متوسط', en: 'Med', fr: 'Moyen', tr: 'Orta', es: 'Med' },
  'heatmap.highDensity': { ar: 'مرتفع', en: 'High', fr: 'Élevé', tr: 'Yüksek', es: 'Alto' },

  // ─── Sentiment Dashboard ───────────────────────────────
  'sentiment.title': { ar: 'تحليل مشاعر وسائل التواصل', en: 'Social Media Sentiment', fr: 'Analyse du Sentiment des Réseaux Sociaux', tr: 'Sosyal Medya Duygu Analizi', es: 'Análisis de Sentimiento en Redes Sociales' },
  'sentiment.live': { ar: 'مباشر', en: 'LIVE', fr: 'EN DIRECT', tr: 'CANLI', es: 'EN VIVO' },
  'sentiment.riskIndex': { ar: 'مؤشر مشاعر المخاطر', en: 'Risk Sentiment Index', fr: 'Indice de Sentiment de Risque', tr: 'Risk Duygu İndeksi', es: 'Índice de Sentimiento de Riesgo' },
  'sentiment.alertNormal': { ar: 'طبيعي', en: 'Normal', fr: 'Normal', tr: 'Normal', es: 'Normal' },
  'sentiment.alertElevated': { ar: 'مرتفع', en: 'Elevated', fr: 'Élevé', tr: 'Yüksek', es: 'Elevado' },
  'sentiment.alertHigh': { ar: 'عالي', en: 'High', fr: 'Élevé', tr: 'Çok Yüksek', es: 'Alto' },
  'sentiment.alertCritical': { ar: 'حرج', en: 'Critical', fr: 'Critique', tr: 'Kritik', es: 'Crítico' },
  'sentiment.overall': { ar: 'المشاعر العامة', en: 'Overall Sentiment', fr: 'Sentiment Général', tr: 'Genel Duygu', es: 'Sentimiento General' },
  'sentiment.velocity': { ar: 'السرعة', en: 'Velocity', fr: 'Vélocité', tr: 'Hız', es: 'Velocidad' },
  'sentiment.volume': { ar: 'الحجم', en: 'Volume', fr: 'Volume', tr: 'Hacim', es: 'Volumen' },
  'sentiment.last72Hours': { ar: 'آخر 72 ساعة', en: 'Last 72 Hours', fr: 'Dernières 72 Heures', tr: 'Son 72 Saat', es: 'Últimas 72 Horas' },
  'sentiment.sentiment': { ar: 'المشاعر', en: 'Sentiment', fr: 'Sentiment', tr: 'Duygu', es: 'Sentimiento' },
  'sentiment.risk': { ar: 'المخاطر', en: 'Risk', fr: 'Risque', tr: 'Risk', es: 'Riesgo' },
  'sentiment.trendingTopics': { ar: 'المواضيع الرائدة', en: 'Trending Topics', fr: 'Sujets Tendance', tr: 'Trend Konular', es: 'Temas Tendencia' },
  'sentiment.alerts': { ar: 'تنبيهات المشاعر', en: 'Sentiment Alerts', fr: 'Alertes de Sentiment', tr: 'Duygu Uyarıları', es: 'Alertas de Sentimiento' },
  'sentiment.verified': { ar: 'مؤكد', en: 'Verified', fr: 'Vérifié', tr: 'Doğrulanmış', es: 'Verificado' },
  'sentiment.allCountries': { ar: 'نظرة عامة على جميع الدول', en: 'All Countries Overview', fr: 'Aperçu de Tous les Pays', tr: 'Tüm Ülkeler Genel Bakış', es: 'Resumen de Todos los Países' },
  'sentiment.disclaimer': { ar: 'إشارات وسائل التواصل تسبق الأخبار التقليدية بـ 12-48 ساعة. البيانات محاكاة لأغراض العرض.', en: 'Social signals precede traditional news by 12-48 hours. Data is simulated for demonstration.', fr: 'Les signaux sociaux précèdent les nouvelles traditionnelles de 12 à 48 heures. Les données sont simulées à des fins de démonstration.', tr: 'Sosyal sinyaller geleneksel haberlerden 12-48 saat önce gelir. Veriler gösterim amacıyla simüle edilmiştir.', es: 'Las señales sociales preceden a las noticias tradicionales en 12-48 horas. Los datos son simulados con fines de demostración.' },

  // ─── Economic Impact Panel ─────────────────────────────
  'economic.title': { ar: 'نمذجة التأثير الاقتصادي', en: 'Economic Impact Modeling', fr: 'Modélisation de l\'Impact Économique', tr: 'Ekonomik Etki Modelleme', es: 'Modelado de Impacto Económico' },
  'economic.subtitle': { ar: 'على غرار نموذج BlackRock — VaR مشروط بالأحداث الجيوسياسية', en: 'BlackRock-style — Geopolitical Conditional VaR', fr: 'Style BlackRock — VaR conditionnel géopolitique', tr: 'BlackRock tarzı — Jeopolitik Koşullu VaR', es: 'Estilo BlackRock — VaR condicional geopolítico' },
  'economic.expectedLoss': { ar: 'الخسارة المتوقعة', en: 'Expected Loss', fr: 'Perte Attendue', tr: 'Beklenen Kayıp', es: 'Pérdida Esperada' },
  'economic.var95': { ar: 'VaR (95%)', en: 'VaR (95%)', fr: 'VaR (95%)', tr: 'VaR (95%)', es: 'VaR (95%)' },
  'economic.cvar95': { ar: 'CVaR (95%)', en: 'CVaR (95%)', fr: 'CVaR (95%)', tr: 'CVaR (95%)', es: 'CVaR (95%)' },
  'economic.scenarioProb': { ar: 'احتمال السيناريو', en: 'Scenario Prob.', fr: 'Prob. du Scénario', tr: 'Senaryo Olasılığı', es: 'Prob. del Escenario' },
  'economic.assetImpacts': { ar: 'تأثير الأصول', en: 'Asset Impacts', fr: 'Impacts sur les Actifs', tr: 'Varlık Etkileri', es: 'Impactos en Activos' },
  'economic.varLabel': { ar: 'VaR:', en: 'VaR:', fr: 'VaR:', tr: 'VaR:', es: 'VaR:' },
  'economic.diversificationScore': { ar: 'درجة التنويع ضد المخاطر الجيوسياسية', en: 'Geo-Risk Diversification Score', fr: 'Score de Diversification Géo-Risque', tr: 'Jeopolitik Risk Çeşitlendirme Skoru', es: 'Puntuación de Diversificación Geo-Riesgo' },
  'economic.stressTests': { ar: 'اختبارات الضغط', en: 'Stress Tests', fr: 'Tests de Stress', tr: 'Stres Testleri', es: 'Pruebas de Estrés' },
  'economic.worstAsset': { ar: 'أسوأ أصل', en: 'Worst asset', fr: 'Pire actif', tr: 'En kötü varlık', es: 'Peor activo' },
  'economic.recovery': { ar: 'تعافي', en: 'Recovery', fr: 'Récupération', tr: 'Toparlanma', es: 'Recuperación' },
  'economic.months': { ar: 'شهور', en: 'months', fr: 'mois', tr: 'ay', es: 'meses' },
  'economic.supplyChainImpact': { ar: 'تأثير سلاسل التوريد', en: 'Supply Chain Impact', fr: 'Impact sur la Chaîne d\'Approvisionnement', tr: 'Tedarik Zinciri Etkisi', es: 'Impacto en la Cadena de Suministro' },
  'economic.tradeAtRisk': { ar: 'التجارة المعرضة للخطر', en: 'Trade at risk', fr: 'Commerce à risque', tr: 'Risk altındaki ticaret', es: 'Comercio en riesgo' },
  'economic.estimatedCost': { ar: 'تكلفة محتملة', en: 'Estimated cost', fr: 'Coût estimé', tr: 'Tahmini maliyet', es: 'Costo estimado' },
  'economic.ofGdp': { ar: 'من الناتج المحلي الإجمالي', en: 'of GDP', fr: 'du PIB', tr: 'GSYİH\'nın', es: 'del PIB' },

  // ─── GNN Correlation Graph ─────────────────────────────
  'gnn.title': { ar: 'تحليل الارتباطات العابرة للحدود', en: 'Cross-border Correlation Analysis', fr: 'Analyse des Corrélations Transfrontalières', tr: 'Sınır Ötesi Korelasyon Analizi', es: 'Análisis de Correlación Transfronteriza' },
  'gnn.subtitle': { ar: 'شبكات الرسم البياني العصبية لاكتشاف المخاطر النظامية', en: 'Graph Neural Networks for systemic risk detection', fr: 'Réseaux de Neurones sur Graphes pour la détection des risques systémiques', tr: 'Sistemik risk tespiti için Grafik Sinir Ağları', es: 'Redes Neuronales de Grafos para la detección de riesgos sistémicos' },
  'gnn.systemicRisk': { ar: 'مخطر نظامي', en: 'Systemic Risk', fr: 'Risque Systémique', tr: 'Sistemik Risk', es: 'Riesgo Sistémico' },
  'gnn.filterAll': { ar: 'الكل', en: 'All', fr: 'Tous', tr: 'Tümü', es: 'Todos' },
  'gnn.filterTrade': { ar: 'تجارة', en: 'Trade', fr: 'Commerce', tr: 'Ticaret', es: 'Comercio' },
  'gnn.filterAlliance': { ar: 'تحالف', en: 'Alliance', fr: 'Alliance', tr: 'İttifak', es: 'Alianza' },
  'gnn.filterConflict': { ar: 'صراع', en: 'Conflict', fr: 'Conflit', tr: 'Çatışma', es: 'Conflicto' },
  'gnn.filterSanctions': { ar: 'عقوبات', en: 'Sanctions', fr: 'Sanctions', tr: 'Yaptırımlar', es: 'Sanciones' },
  'gnn.filterSupply': { ar: 'سلسلة توريد', en: 'Supply', fr: 'Approvisionnement', tr: 'Tedarik', es: 'Suministro' },
  'gnn.vulnerableClusters': { ar: 'المجموعات الضعيفة', en: 'Vulnerable Clusters', fr: 'Clusters Vulnérables', tr: 'Savunmasız Kümeler', es: 'Clústeres Vulnerables' },
  'gnn.hiddenRisks': { ar: 'المخاطر الخفية', en: 'Hidden Risks', fr: 'Risques Cachés', tr: 'Gizli Riskler', es: 'Riesgos Ocultos' },
  'gnn.probability': { ar: 'الاحتمال', en: 'Prob', fr: 'Prob.', tr: 'Olasılık', es: 'Prob.' },
  'gnn.type': { ar: 'النوع', en: 'Type', fr: 'Type', tr: 'Tür', es: 'Tipo' },

  // ─── Country Risk Detail / Sheet ──────────────────────
  'country.riskBreakdown': { ar: 'تفصيل المخاطر', en: 'Risk Breakdown', fr: 'Répartition des Risques', tr: 'Risk Dağılımı', es: 'Desglose de Riesgo' },
  'country.recentEvents': { ar: 'أحدث الأحداث', en: 'Recent Events', fr: 'Événements Récents', tr: 'Son Olaylar', es: 'Eventos Recientes' },
  'country.affectedMarkets': { ar: 'الأسواق المتأثرة', en: 'Affected Markets', fr: 'Marchés Affectés', tr: 'Etkilenen Piyasalar', es: 'Mercados Afectados' },
  'country.fullAnalysis': { ar: 'التحليل الكامل', en: 'Full Analysis', fr: 'Analyse Complète', tr: 'Tam Analiz', es: 'Análisis Completo' },
  'country.detailsTitle': { ar: 'تفاصيل المخاطر الجيوسياسية', en: 'Geopolitical Risk Details', fr: 'Détails des Risques Géopolitiques', tr: 'Jeopolitik Risk Detayları', es: 'Detalles de Riesgo Geopolítico' },

  // ─── Confidence Interval Badge ─────────────────────────
  'confidence.ci95': { ar: 'ف.ث 95%:', en: '95% CI:', fr: 'IC 95%:', tr: '%95 GA:', es: 'IC 95%:' },
  'confidence.sampleSize': { ar: 'عينة=', en: 'n=', fr: 'n=', tr: 'n=', es: 'n=' },

  // ─── Network Graph ────────────────────────────────────
  'network.title': { ar: 'شبكة التحالفات والصراعات', en: 'Alliance & Conflict Network', fr: 'Réseau d\'Alliances et de Conflits', tr: 'İttifak ve Çatışma Ağı', es: 'Red de Alianzas y Conflictos' },
  'network.noData': { ar: 'لا توجد بيانات شبكية للعرض', en: 'No network data to display', fr: 'Aucune donnée réseau à afficher', tr: 'Görüntülenecek ağ verisi yok', es: 'No hay datos de red para mostrar' },

  // ─── Scenario Engine ──────────────────────────────────
  'scenarios.simulation': { ar: 'محاكاة السيناريوهات', en: 'Scenario Simulation', fr: 'Simulation de Scénarios', tr: 'Senaryo Simülasyonu', es: 'Simulación de Escenarios' },
  'scenarios.scenario': { ar: 'السيناريو', en: 'Scenario', fr: 'Scénario', tr: 'Senaryo', es: 'Escenario' },
  'scenarios.duration': { ar: 'المدة', en: 'Duration', fr: 'Durée', tr: 'Süre', es: 'Duración' },
  'scenarios.probDistribution': { ar: 'توزيع الاحتمالات', en: 'Probability Distribution', fr: 'Distribution des Probabilités', tr: 'Olasılık Dağılımı', es: 'Distribución de Probabilidades' },

  // ─── Bayesian Escalation Ladder ───────────────────────
  'bayesian.corroborated': { ar: 'موثّق', en: 'Corroborated', fr: 'Corroboré', tr: 'Doğrulanmış', es: 'Corroborado' },
  'bayesian.reliability': { ar: 'موثوقية', en: 'Reliability', fr: 'Fiabilité', tr: 'Güvenilirlik', es: 'Fiabilidad' },
  'bayesian.severity': { ar: 'شدة', en: 'Sev.', fr: 'Grav.', tr: 'Şid.', es: 'Grav.' },

  // ─── Risk Levels — full labels for all 5 langs ──────
//   'risk.low': { ar: 'منخفض', en: 'Low', fr: 'Faible', tr: 'Düşük', es: 'Bajo' },
//   'risk.moderate': { ar: 'معتدل', en: 'Moderate', fr: 'Modéré', tr: 'Orta', es: 'Moderado' },
//   'risk.elevated': { ar: 'مرتفع', en: 'Elevated', fr: 'Élevé', tr: 'Yüksek', es: 'Elevado' },
//   'risk.high': { ar: 'عالي', en: 'High', fr: 'Élevé', tr: 'Çok Yüksek', es: 'Alto' },
//   'risk.severe': { ar: 'شديد', en: 'Severe', fr: 'Sévère', tr: 'Aşırı', es: 'Grave' },
  'risk.critical': { ar: 'حرج', en: 'Critical', fr: 'Critique', tr: 'Kritik', es: 'Crítico' },
};

/**
 * Get a translated string for the geopolitical section.
 * Falls back to English if the locale is not found, then to the key itself.
 */
export function t(key: string, locale: string): string {
  const entry = geoTranslations[key];
  if (!entry) return key;
  const loc = (locale as GeoLocale) in entry ? (locale as GeoLocale) : 'en';
  return entry[loc] || entry.en || key;
}

/**
 * Extract translations for a specific locale only.
 * This enables code-splitting: components can import only the locale they need
 * instead of bundling all 5 locales.
 *
 * @param locale - The locale to extract
 * @returns A flat key→string map for the given locale
 */
export function getTranslationsForLocale(locale: GeoLocale): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [key, entry] of Object.entries(geoTranslations)) {
    result[key] = entry[locale] || entry.en || key;
  }
  return result;
}

/**
 * Lightweight translate function for a single locale.
 * Useful when you already have the locale-specific translations map.
 */
export function tLocale(translations: Record<string, string>, key: string): string {
  return translations[key] || key;
}

/**
 * Time ago helper that respects the current locale.
 */
export function timeAgoLocalized(dateStr: string, locale: string): string {
  try {
    const date = new Date(dateStr);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMin = Math.floor(diffMs / 60000);
    if (diffMin < 1) return t('time.now', locale);
    if (diffMin < 60) return `${diffMin} ${t('time.minute', locale)}`;
    const diffHr = Math.floor(diffMin / 60);
    if (diffHr < 24) return `${diffHr} ${t('time.hour', locale)}`;
    const diffDay = Math.floor(diffHr / 24);
    if (diffDay < 30) return `${diffDay} ${t('time.day', locale)}`;
    const diffMonth = Math.floor(diffDay / 30);
    return `${diffMonth} ${t('time.month', locale)}`;
  } catch {
    return '';
  }
}
