/**
 * ROUAA Product Catalog — Data Layer
 * 44 products across 7 categories
 * Each product has: id, name, category, description, industries, roles,
 * deploy type, evidence chain, key features, pricing, integration
 */

const ROUAA_PRODUCTS = [
  // === MEDIA (8) ===
  {
    id: 'med-news-engine',
    cat: 'media',
    nameEn: 'Financial Publishing Platform',
    tagline: 'Turn official events into ready-to-publish news',
    desc: 'A complete engine that captures official financial events, extracts facts, writes news in a professional editorial style, and publishes it in 6 languages — in under 30 seconds.',
    industries: ['media', 'fintech'],
    roles: ['editor', 'cto'],
    deploy: ['saas', 'whitelabel', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Media',
    evidence: 'Every news item carries a complete evidence chain — from source to fact',
    features: ['Automated event discovery', 'Customizable editorial-style generation', '6 languages', 'Direct source linking'],
    pricing: 'from $1K/mo',
    integration: 'REST API · Webhook · White-label embed',
  },
  {
    id: 'med-agency',
    cat: 'media',
    nameEn: 'News Production Agent',
    tagline: 'A complete financial news agency under your organization\'s name',
    desc: 'Not just a writing tool. An intelligent agent that produces original content — not copies from other agencies. It monitors, analyzes, writes, edits, publishes — under your brand.',
    industries: ['media'],
    roles: ['editor'],
    deploy: ['saas', 'whitelabel'],
    type: 'agent',
    maturity: 'early',
    buyer: 'Media',
    evidence: 'Every story is traceable to its official source',
    features: ['Original production, not copying', 'Trainable style', 'Self-editing', 'Multi-channel publishing'],
    pricing: 'from $5K/mo',
    integration: 'CMS · WordPress · Custom',
  },
  {
    id: 'med-reports',
    cat: 'media',
    nameEn: 'Automated Research Reports',
    tagline: 'Daily, weekly, and sector reports — every figure verified',
    desc: 'Periodic reports built automatically from official events — daily, weekly, sectoral, geographic. Every figure is verified with its source.',
    industries: ['media', 'fintech'],
    roles: ['editor', 'head'],
    deploy: ['saas', 'whitelabel'],
    type: 'application',
    maturity: 'production',
    buyer: 'Media',
    evidence: 'Every report carries a footer with all sources used',
    features: ['Periodic scheduling', 'Customizable templates', 'PDF/HTML export', 'Verified archiving'],
    pricing: 'from $5K/mo',
    integration: 'Email · CMS · FTP · API',
  },
  {
    id: 'med-video',
    cat: 'media',
    nameEn: 'Video Pipeline',
    tagline: 'Distribution channel for verified financial intelligence',
    desc: 'From a verified official event to a multi-channel analytical video: script, voiceover, graphics, subtitles. The video is just an output — verified intelligence is the core.',
    industries: ['media'],
    roles: ['editor'],
    deploy: ['saas', 'whitelabel'],
    type: 'application',
    maturity: 'preview',
    buyer: 'Media',
    evidence: 'Every figure in the video is verified in the description',
    features: ['Smart script', 'Professional voiceover', 'Automated graphics', '6-language subtitles'],
    pricing: 'from $10K/mo',
    integration: 'YouTube · MP4 export · CMS',
  },
  {
    id: 'med-infographic',
    cat: 'media',
    nameEn: 'Infographic Pipeline',
    tagline: 'Infographics from official data in seconds',
    desc: 'Turn official figures into professional visual infographics — automatically. Every design carries a footer with the source.',
    industries: ['media', 'fintech'],
    roles: ['editor'],
    deploy: ['saas', 'api'],
    type: 'application',
    maturity: 'preview',
    buyer: 'Media',
    evidence: 'Every chart carries a source citation',
    features: ['Sector templates', 'PNG/SVG export', 'Full customization', 'Embedded source'],
    pricing: 'from $3K/mo',
    integration: 'CMS · API · CDN',
  },
  {
    id: 'med-audio',
    cat: 'media',
    nameEn: 'Audio Intelligence',
    tagline: 'Audio distribution for verified financial intelligence',
    desc: 'A daily audio channel that distributes verified financial intelligence — script and production directly from official events. The podcast is just a channel, the intelligence is the content.',
    industries: ['media'],
    roles: ['editor'],
    deploy: ['saas'],
    type: 'application',
    maturity: 'preview',
    buyer: 'Media',
    evidence: 'Every episode carries source links',
    features: ['Smart script', 'Professional audio', 'Intro music', 'Ready RSS'],
    pricing: 'from $4K/mo',
    integration: 'Spotify · Apple · RSS',
  },
  {
    id: 'med-calendar',
    cat: 'media',
    nameEn: 'Economic Calendar',
    tagline: 'A smart economic calendar — not just dates',
    desc: 'Every event in the calendar carries: forecast, previous, actual, expected impact, verified context — not just a number.',
    industries: ['media', 'fintech'],
    roles: ['editor', 'cto'],
    deploy: ['saas', 'api', 'whitelabel'],
    type: 'application',
    maturity: 'production',
    buyer: 'Media',
    evidence: 'Every event is linked to its official source',
    features: ['Proactive alerts', 'Expected impact', 'Historical context', '6 languages'],
    pricing: 'from $2K/mo',
    integration: 'API · Widget · Embed',
  },
  {
    id: 'med-pulse',
    cat: 'media',
    nameEn: 'Daily Intelligence Pulse',
    tagline: '5 minutes to read what matters — verified',
    desc: 'A concise daily briefing that selects the 5-7 most important financial events, writes a brief verified analysis for each, and is delivered to your inbox before market open.',
    industries: ['media', 'funds'],
    roles: ['editor'],
    deploy: ['saas'],
    type: 'application',
    maturity: 'production',
    buyer: 'Media',
    evidence: 'Every event links to its source',
    features: ['Interest-based customization', '6 languages', 'Email delivery', 'Searchable archive'],
    pricing: 'from $1.5K/mo',
    integration: 'Email · Webhook · API',
  },

  // === TRADING (9) ===
  {
    id: 'trd-dashboard',
    cat: 'trading',
    nameEn: 'Trading Intelligence Dashboard',
    tagline: 'Context behind every trade — inside your platform',
    desc: 'A panel that appears inside the broker\'s platform — showing for every trade: the event that moved it, the verified facts, its impact on the portfolio.',
    industries: ['brokers', 'banks', 'fintech'],
    roles: ['broker', 'cto'],
    deploy: ['api', 'whitelabel', 'saas'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every context carries the evidence chain',
    features: ['Full customization', 'Night/day mode', 'Multi-device', 'Arabic translation'],
    pricing: 'from $8K/mo',
    integration: 'REST · WebSocket · iframe embed',
  },
  {
    id: 'trd-chart',
    cat: 'trading',
    nameEn: 'Smart Chart Annotations',
    tagline: 'You see the chart — and understand "why" at every turning point',
    desc: 'A smart overlay on charts that explains: why did the price move here? Which official event caused this shift? What is the verified context?',
    industries: ['brokers', 'fintech'],
    roles: ['broker', 'cto'],
    deploy: ['api', 'whitelabel'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every annotation links to a verified event',
    features: ['Automated annotations', 'Event overlay', 'Export', 'Customization'],
    pricing: 'from $5K/mo',
    integration: 'TradingView · Custom · API',
  },
  {
    id: 'trd-portfolio',
    cat: 'trading',
    nameEn: 'Portfolio Intelligence',
    tagline: 'How every event affects your portfolio — before it does',
    desc: 'An engine that analyzes the client\'s portfolio, links it to the Knowledge Graph, and alerts: this event will affect 4 stocks in your portfolio in this way.',
    industries: ['brokers', 'funds'],
    roles: ['broker', 'cio'],
    deploy: ['api', 'saas', 'enterprise'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every alert carries an exposure analysis',
    features: ['Real-time analysis', 'Proactive alerts', 'Scenarios', 'Hedging suggestions'],
    pricing: 'from $7K/mo',
    integration: 'REST · Webhook · SDK',
  },
  {
    id: 'trd-assistant',
    cat: 'trading',
    nameEn: 'Trading Assistant',
    tagline: 'The client asks "why this stock?" — the assistant answers with verification',
    desc: 'A smart assistant inside the platform that answers client questions: "what\'s the impact of the interest rate decision?", "why did this stock move?" — every answer is verified.',
    industries: ['brokers', 'fintech'],
    roles: ['broker'],
    deploy: ['saas', 'whitelabel', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every answer carries source links',
    features: ['Natural language chat', 'Verified answers', 'Multilingual', 'Learns from interaction'],
    pricing: 'from $6K/mo',
    integration: 'Web Chat · Mobile SDK · API',
  },
  {
    id: 'trd-lab',
    cat: 'trading',
    nameEn: 'Investment Strategy Intelligence Lab',
    tagline: 'Test your strategies on verified events',
    desc: 'A backtesting lab that simulates the client\'s strategy on verified historical events — not just historical prices, but full context.',
    industries: ['brokers', 'funds'],
    roles: ['broker', 'cio', 'head'],
    deploy: ['saas', 'enterprise'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every test point carries its verified context',
    features: ['5-year simulation', 'What-if scenarios', 'Performance analysis', 'Report export'],
    pricing: 'from $15K/mo',
    integration: 'API · SDK · Export',
  },
  {
    id: 'trd-ai-council',
    cat: 'trading',
    nameEn: 'Multi-Agent Market Intelligence System',
    tagline: 'Multi-agent reasoning with traceable validation steps',
    desc: 'A multi-agent reasoning system with traceable validation steps. Every analysis goes through peer review before publication — only consensus is published.',
    industries: ['brokers', 'funds'],
    roles: ['broker', 'cio'],
    deploy: ['api', 'enterprise'],
    type: 'agent',
    maturity: 'preview',
    buyer: 'Trading',
    evidence: 'Every analysis shows who agreed and who objected',
    features: ['Multi-agent reasoning', 'Consensus mechanism', 'Peer review', 'Dissent log'],
    pricing: 'from $20K/mo',
    integration: 'API · Webhook',
  },
  {
    id: 'trd-auto',
    cat: 'trading',
    nameEn: 'Trading Workflow Automation',
    tagline: 'Predefined trading workflow automation with full audit trail',
    desc: 'A workflow automation engine that applies client-predefined rules. Insights do not suggest trades, they execute what the client has decided — with a full reviewable audit trail.',
    industries: ['brokers', 'funds'],
    roles: ['broker', 'cio'],
    deploy: ['enterprise', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every trade is logged with its decision and chain',
    features: ['Programmable rules', 'Risk limits', 'Full log', 'Safe stop'],
    pricing: 'from $25K/mo',
    integration: 'FIX · REST · Broker APIs',
  },
  {
    id: 'trd-prediction',
    cat: 'trading',
    nameEn: 'Scenario Intelligence Engine',
    tagline: 'Future scenarios — with their probabilities',
    desc: 'For every upcoming event, it generates 3-5 potential scenarios with their probabilities. Not a single prediction — transparent probabilities.',
    industries: ['brokers', 'funds'],
    roles: ['broker', 'head'],
    deploy: ['api', 'saas'],
    type: 'application',
    maturity: 'production',
    buyer: 'Trading',
    evidence: 'Every scenario carries its verified logic',
    features: ['Multiple scenarios', 'Updated probabilities', 'Historical comparison', 'Change alerts'],
    pricing: 'from $10K/mo',
    integration: 'API · Widget · Webhook',
  },
  {
    id: 'trd-content',
    cat: 'trading',
    nameEn: 'Market Commentary Agent',
    tagline: 'Daily content for the broker — under its brand',
    desc: 'An agent that writes daily analyses, market memos, event commentary — all under the broker\'s name, verified, ready to publish.',
    industries: ['brokers'],
    roles: ['broker'],
    deploy: ['saas', 'whitelabel'],
    type: 'agent',
    maturity: 'early',
    buyer: 'Trading',
    evidence: 'Every article carries its sources',
    features: ['Voice customization', 'Publishing schedule', 'Multi-channel', 'Translation'],
    pricing: 'from $4K/mo',
    integration: 'CMS · Email · API',
  },

  // === RESEARCH (6) ===
  {
    id: 'res-brief',
    cat: 'research',
    nameEn: 'Intelligence Brief Generator',
    tagline: 'A committee-ready decision memo — in minutes',
    desc: 'From a market event to a complete decision memo: the thesis, verified facts, scenarios, recommendation, every figure linked to its source.',
    industries: ['funds', 'banks'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'enterprise', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every memo is a complete evidence chain',
    features: ['Committee templates', 'PDF/DOCX export', 'Team comments', 'Verified archiving'],
    pricing: 'from $8K/mo',
    integration: 'REST · Webhook · Export',
  },
  {
    id: 'res-committee',
    cat: 'research',
    nameEn: 'Committee Prep Engine',
    tagline: 'Prepare an investment committee in minutes — not days',
    desc: 'An engine that prepares the investment committee meeting: agenda, memos, expected questions, supporting data — all verified.',
    industries: ['funds', 'banks'],
    roles: ['cio', 'head'],
    deploy: ['enterprise', 'saas'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every agenda item is verified',
    features: ['Automated agenda', 'Memo per item', 'Expected questions', 'Secure distribution'],
    pricing: 'from $12K/mo',
    integration: 'Email · Calendar · REST',
  },
  {
    id: 'res-comparison',
    cat: 'research',
    nameEn: 'Sector Comparison',
    tagline: 'Compare companies on verified criteria — not opinions',
    desc: 'Compare companies within a sector on objective verified criteria — from official data. No analyst opinions.',
    industries: ['funds', 'banks'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every comparison criterion is verified with a source',
    features: ['Customizable criteria', 'Excel export', 'Charts', 'Automated updates'],
    pricing: 'from $6K/mo',
    integration: 'API · Excel · Web',
  },
  {
    id: 'res-deepdive',
    cat: 'research',
    nameEn: 'Deep Dive Reports',
    tagline: 'A 50-page report on a company — in 10 minutes',
    desc: 'A comprehensive report on any company: history, financials, sector, competitors, risks, scenarios — fully verified.',
    industries: ['funds', 'banks'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'enterprise'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every section is verified with sources',
    features: ['50+ pages', 'Charts', 'SWOT analysis', 'PDF export'],
    pricing: 'from $15K/mo',
    integration: 'PDF · REST · Export',
  },
  {
    id: 'res-watchlist',
    cat: 'research',
    nameEn: 'Smart Watchlist',
    tagline: 'Smart monitoring — alerts only for what truly matters',
    desc: 'A watchlist that alerts only when an event is truly impactful — no noise. Every alert carries why it matters and its impact.',
    industries: ['funds'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every alert is verified',
    features: ['Smart filtering', 'Custom alerts', 'Prioritization', 'Archive'],
    pricing: 'from $4K/mo',
    integration: 'API · Email · Push',
  },
  {
    id: 'res-screening',
    cat: 'research',
    nameEn: 'Investment Screener',
    tagline: 'Search for companies using verified criteria',
    desc: 'A screener that uses verified financial criteria — not estimates. Search for: companies with P/E below 15 and revenue growth of 20%+.',
    industries: ['funds', 'banks'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every result is verified with a source',
    features: ['Advanced criteria', 'Save strategies', 'Alerts', 'Export'],
    pricing: 'from $5K/mo',
    integration: 'API · Excel · Web',
  },

  // === RISK (5) ===
  {
    id: 'risk-monitor',
    cat: 'risk',
    nameEn: 'Risk Event Monitor',
    tagline: 'From a global event to a risk alert — in seconds',
    desc: 'A 24/7 monitor of geopolitical and economic events that may affect the portfolio — with instant impact assessment.',
    industries: ['banks', 'govt', 'funds'],
    roles: ['cro', 'treasury'],
    deploy: ['enterprise', 'saas', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Compliance',
    evidence: 'Every alert is verified with 3+ sources',
    features: ['24/7 monitoring', 'Automated classification', 'Tiered alerts', 'Archive'],
    pricing: 'from $15K/mo',
    integration: 'API · Webhook · Email · SMS',
  },
  {
    id: 'risk-exposure',
    cat: 'risk',
    nameEn: 'Exposure Analysis',
    tagline: 'Reveal your portfolio\'s exposure — in real time',
    desc: 'An engine that analyzes your portfolio, links it to the Knowledge Graph, and reveals your exposure to every event: 47 companies in your portfolio are affected by this event.',
    industries: ['banks', 'funds'],
    roles: ['cro', 'treasury'],
    deploy: ['enterprise', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Compliance',
    evidence: 'Every exposure analysis is verified',
    features: ['Real-time analysis', 'Sector impact', 'Geographic impact', 'Scenarios'],
    pricing: 'from $20K/mo',
    integration: 'API · SDK · Export',
  },
  {
    id: 'risk-scenario',
    cat: 'risk',
    nameEn: 'Risk Scenario Engine',
    tagline: '3 scenarios for every event — with their probabilities',
    desc: 'For every risk event, it generates 3 scenarios (base, optimistic, pessimistic) with their probabilities and portfolio impact.',
    industries: ['banks', 'funds'],
    roles: ['cro'],
    deploy: ['enterprise', 'api'],
    type: 'application',
    maturity: 'production',
    buyer: 'Compliance',
    evidence: 'Every scenario carries its logic',
    features: ['3+ scenarios', 'Dynamic probabilities', 'Portfolio impact', 'Historical comparison'],
    pricing: 'from $18K/mo',
    integration: 'API · SDK · Webhook',
  },
  {
    id: 'risk-action',
    cat: 'risk',
    nameEn: 'Action Recommendations',
    tagline: 'Portfolio action recommendations — verified',
    desc: 'Action recommendations: hedge, rebalance, reduce exposure. Every recommendation is verified with its logic — the final decision is yours.',
    industries: ['banks', 'funds'],
    roles: ['cro', 'treasury'],
    deploy: ['enterprise', 'api'],
    type: 'application',
    maturity: 'enterprise',
    buyer: 'Compliance',
    evidence: 'Every recommendation is verified with its logic',
    features: ['Action recommendations', 'Cost/benefit analysis', 'Execution tracking', 'Post-review'],
    pricing: 'from $12K/mo',
    integration: 'API · Trading Systems',
  },
  {
    id: 'risk-compliance',
    cat: 'risk',
    nameEn: 'Compliance Audit',
    tagline: 'A complete log — ready for regulators',
    desc: 'A complete audit log: every risk decision, every recommendation, every action — verified with a timestamp, exportable for regulators.',
    industries: ['banks', 'govt'],
    roles: ['cro', 'treasury'],
    deploy: ['enterprise'],
    type: 'application',
    maturity: 'enterprise',
    buyer: 'Compliance',
    evidence: 'Every log is immutable',
    features: ['Millisecond log', 'Regulatory export', 'Advanced search', '7-year retention'],
    pricing: 'from $25K/mo',
    integration: 'Regulatory · API · Export',
  },

  // === APIs (7) ===
  {
    id: 'api-events',
    cat: 'api',
    nameEn: 'Events API',
    tagline: 'All verified financial events — JSON',
    desc: 'A REST API that returns all verified financial events with: type, source, facts, evidence, impact. Clean JSON.',
    industries: ['fintech', 'brokers', 'media'],
    roles: ['cto', 'founder'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every response carries the evidence chain',
    features: ['REST · JSON', 'Advanced filtering', 'Pagination', 'WebSocket stream'],
    pricing: 'from $2K/mo',
    integration: 'REST · WebSocket · SDK',
  },
  {
    id: 'api-facts',
    cat: 'api',
    nameEn: 'Facts API',
    tagline: 'Query any verified financial fact',
    desc: 'Query: "What are Aramco\'s 2025 revenues?" — you get the fact + source + page + paragraph.',
    industries: ['fintech', 'brokers', 'media'],
    roles: ['cto', 'founder'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every fact carries its complete evidence',
    features: ['Natural language query', 'Instant response', 'Verified accuracy', 'Real-time updates'],
    pricing: 'from $3K/mo',
    integration: 'REST · GraphQL · SDK',
  },
  {
    id: 'api-sources',
    cat: 'api',
    nameEn: 'Sources API',
    tagline: '411 official sources — searchable',
    desc: 'Explore 411 official sources: central banks, regulators, exchanges, companies. Each source has a trust score and history.',
    industries: ['fintech', 'brokers'],
    roles: ['cto'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every source is verified',
    features: ['Advanced search', 'Sector filtering', 'Trust score', 'Update history'],
    pricing: 'from $1K/mo',
    integration: 'REST · SDK',
  },
  {
    id: 'api-evidence',
    cat: 'api',
    nameEn: 'Evidence API',
    tagline: 'Extract the evidence chain for any fact',
    desc: 'Give it any fact, it returns the complete evidence chain: source ← document ← page ← paragraph ← fact.',
    industries: ['fintech', 'banks'],
    roles: ['cto'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Returns the complete chain',
    features: ['Instant retrieval', 'Structured JSON', 'Snippet images', 'Independent verification'],
    pricing: 'from $2K/mo',
    integration: 'REST · SDK · Webhook',
  },
  {
    id: 'api-insights',
    cat: 'api',
    nameEn: 'Insights API',
    tagline: 'Ready-made intelligence — with evidence',
    desc: 'Intelligence generated from events: summary, analysis, impact, scenarios. Every insight carries its evidence.',
    industries: ['fintech', 'brokers'],
    roles: ['cto', 'founder'],
    deploy: ['api'],
    type: 'api',
    maturity: 'enterprise',
    buyer: 'Engineering',
    evidence: 'Every insight carries its evidence',
    features: ['Real-time insights', 'Multilingual', 'Customization', 'Webhook'],
    pricing: 'from $5K/mo',
    integration: 'REST · WebSocket · SDK',
  },
  {
    id: 'api-streaming',
    cat: 'api',
    nameEn: 'Streaming API',
    tagline: 'Real-time events — via WebSocket',
    desc: 'Real-time streaming of all financial events as they occur — with facts and evidence. No polling, instant events.',
    industries: ['fintech', 'brokers'],
    roles: ['cto'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every event in the stream carries its evidence',
    features: ['WebSocket', 'Low latency', 'Selective subscriptions', 'Safe retries'],
    pricing: 'from $4K/mo',
    integration: 'WebSocket · SDK',
  },
  {
    id: 'api-sdk',
    cat: 'api',
    nameEn: 'Official SDK',
    tagline: 'Integrate verified intelligence into your products',
    desc: 'An official SDK in multiple languages: Python, JavaScript, Java, Go. Full documentation, examples, support.',
    industries: ['fintech'],
    roles: ['cto', 'founder'],
    deploy: ['api'],
    type: 'api',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every SDK call carries the evidence chain',
    features: ['Python · JS · Java · Go', 'Interactive docs', 'Complete examples', '24/7 support'],
    pricing: 'Free for API customers',
    integration: 'pip · npm · maven · go get',
  },

  // === INTELLIGENCE AGENTS (4) — Specialized AI analysts powered by Evidence Layer + Knowledge Graph + Reasoning Engine ===
  {
    id: 'agt-macro',
    cat: 'agent',
    nameEn: 'Macro Intelligence Agent',
    tagline: 'A macro analyst that works 24/7',
    desc: 'A smart agent specialized in macroeconomics: interest rates, inflation, growth, unemployment. It analyzes, writes, alerts.',
    industries: ['funds', 'banks', 'media', 'brokers'],
    roles: ['cio', 'cro', 'head'],
    deploy: ['saas', 'api', 'enterprise'],
    type: 'agent',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every analysis is verified',
    features: ['Macro analysis', 'Proactive alerts', 'Integration with other agents', 'Continuous learning'],
    pricing: 'from $8K/mo',
    integration: 'API · Webhook · Slack',
  },
  {
    id: 'agt-sector',
    cat: 'agent',
    nameEn: 'Sector Intelligence Agent',
    tagline: 'A sector analyst for every sector',
    desc: 'An agent specialized in a specific sector: energy, banking, technology, real estate. It knows its companies, metrics, indicators.',
    industries: ['funds', 'banks', 'media'],
    roles: ['cio', 'head'],
    deploy: ['saas', 'api'],
    type: 'agent',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every sector analysis is verified',
    features: ['Sector specialization', 'Within-sector comparisons', 'Sector alerts', 'Periodic reports'],
    pricing: 'from $7K/mo',
    integration: 'API · Webhook',
  },
  {
    id: 'agt-risk',
    cat: 'agent',
    nameEn: 'Risk Intelligence Agent',
    tagline: 'A risk officer that works 24/7',
    desc: 'An agent that continuously analyzes risks: geopolitical, market, operational. It alerts before problems occur.',
    industries: ['banks', 'funds', 'brokers'],
    roles: ['cro', 'treasury'],
    deploy: ['enterprise', 'api'],
    type: 'agent',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every risk alert is verified',
    features: ['24/7 monitoring', 'Tiered alerts', 'Scenarios', 'Action recommendations'],
    pricing: 'from $12K/mo',
    integration: 'API · Webhook · Email · SMS',
  },
  {
    id: 'agt-fact-checker',
    cat: 'agent',
    nameEn: 'Fact Verification Agent',
    tagline: 'A fact-checker that works before publication',
    desc: 'An agent that reviews every analysis before publication: is every figure correct? Is every source verified? Is every conclusion coherent?',
    industries: ['funds', 'banks', 'media', 'brokers'],
    roles: ['cio', 'cro', 'cto', 'editor', 'broker', 'head', 'treasury', 'founder'],
    deploy: ['saas', 'api', 'enterprise'],
    type: 'agent',
    maturity: 'production',
    buyer: 'Research',
    evidence: 'Every analysis goes through its review',
    features: ['Automated verification', 'Contradiction detection', 'Source comparison', 'Review log'],
    pricing: 'from $6K/mo',
    integration: 'API · Webhook · CI/CD',
  },

  // === COMPONENTS (5) ===
  {
    id: 'cmp-graph',
    cat: 'component',
    nameEn: 'Knowledge Graph',
    tagline: 'The financial relationships network — API',
    desc: 'An API to access the financial relationships network: companies, sectors, events, individuals. Every node is verified.',
    industries: ['fintech', 'brokers', 'banks', 'media'],
    roles: ['cto', 'founder'],
    deploy: ['api', 'enterprise', 'whitelabel'],
    type: 'component',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every node is verified',
    features: ['Cypher queries', 'Visual exploration', 'Real-time updates', 'GraphML export'],
    pricing: 'from $10K/mo',
    integration: 'REST · GraphQL · Cypher',
  },
  {
    id: 'cmp-source-registry',
    cat: 'component',
    nameEn: 'Source Registry',
    tagline: '411 official sources — accessible',
    desc: 'A database of 411 official sources: central banks, regulators, exchanges. Searchable and filterable.',
    industries: ['fintech', 'brokers', 'banks'],
    roles: ['cto', 'founder'],
    deploy: ['api', 'enterprise'],
    type: 'component',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every source is verified',
    features: ['Advanced search', 'Sector filtering', 'Trust score', 'Full API'],
    pricing: 'from $3K/mo',
    integration: 'REST · SDK',
  },
  {
    id: 'cmp-evidence-store',
    cat: 'component',
    nameEn: 'Evidence Store',
    tagline: 'Immutable storage for all evidence',
    desc: 'Immutable storage for all evidence chains in ROUAA — queryable, exportable, auditable.',
    industries: ['fintech', 'banks', 'brokers'],
    roles: ['cto'],
    deploy: ['api', 'enterprise', 'whitelabel'],
    type: 'component',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every piece of evidence is stored immutably',
    features: ['Permanent storage', 'Advanced query', 'Regulatory export', 'Full API'],
    pricing: 'from $8K/mo',
    integration: 'REST · SDK · Export',
  },
  {
    id: 'cmp-reasoning-engine',
    cat: 'component',
    nameEn: 'Reasoning Engine',
    tagline: 'The multi-agent reasoning engine',
    desc: 'The multi-agent reasoning engine — can be used to produce custom analyses for your needs.',
    industries: ['fintech', 'brokers', 'banks'],
    roles: ['cto', 'founder'],
    deploy: ['api', 'enterprise'],
    type: 'component',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every analysis is verified',
    features: ['Multi-agent reasoning', 'Customizable', 'Peer review', 'Full API'],
    pricing: 'from $20K/mo',
    integration: 'REST · SDK',
  },
  {
    id: 'cmp-audit-trail',
    cat: 'component',
    nameEn: 'Audit Trail',
    tagline: 'A millisecond log for every operation',
    desc: 'A millisecond-precision audit log for every operation in the system — searchable, exportable, auditable.',
    industries: ['fintech', 'banks', 'brokers'],
    roles: ['cto'],
    deploy: ['api', 'enterprise'],
    type: 'component',
    maturity: 'production',
    buyer: 'Engineering',
    evidence: 'Every operation is logged',
    features: ['Millisecond precision', 'Advanced search', 'Regulatory export', '7-year retention'],
    pricing: 'from $7K/mo',
    integration: 'REST · SDK · Export',
  },
];

if (typeof window !== 'undefined') {
  window.ROUAA_PRODUCTS = ROUAA_PRODUCTS;
}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ROUAA_PRODUCTS;
}
