// ─── English Disclaimer Page ─────────────────────────────────────────
// Server Component — Financial Disclaimer for the Rouaa platform

import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer',
  description:
    'Financial disclaimer for the Rouaa platform. Important information about investment risks and the limitations of our financial content.',
};

export default function EnDisclaimerPage() {
  return (
    <main className="min-h-screen" dir="ltr" style={{ background: 'var(--bg)' }}>
      <div className="max-w-4xl mx-auto px-4 pt-6 pb-12">
        {/* Header */}
        <div className="mb-8">
          <h1
            className="text-2xl md:text-3xl font-bold mb-2"
            style={{ color: 'var(--text, #E8EDF5)' }}
          >
            Financial Disclaimer
          </h1>
          <p className="text-sm" style={{ color: 'var(--text3, #8A9DB2)' }}>
            Last updated: March 2025
          </p>
        </div>

        {/* Critical Warning Banner */}
        <div
          className="rounded-2xl p-5 mb-6"
          style={{
            background: 'rgba(255,77,106,0.06)',
            border: '1px solid rgba(255,77,106,0.2)',
          }}
        >
          <div className="flex items-start gap-3">
            <svg
              width="20"
              height="20"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#ff4d6a"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
              style={{ flexShrink: 0, marginTop: '2px' }}
            >
              <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
              <line x1="12" y1="9" x2="12" y2="13" />
              <line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
            <div>
              <p className="text-sm font-bold mb-1" style={{ color: '#ff4d6a' }}>
                Important Risk Warning
              </p>
              <p className="text-xs leading-relaxed" style={{ color: 'var(--text2, #B0C4D8)' }}>
                Trading in financial markets involves substantial risk of loss and is not
                suitable for every investor. The value of investments can go down as well as
                up, and you may lose more than your original investment. Never trade with
                money you cannot afford to lose.
              </p>
            </div>
          </div>
        </div>

        {/* Not Financial Advice */}
        <div
          className="rounded-2xl p-6 md:p-8 mb-6"
          style={{
            background: 'var(--bg-elevated, rgba(255,255,255,0.04))',
            border: '1px solid var(--border-subtle, rgba(255,255,255,0.08))',
          }}
        >
          <h2
            className="text-base font-bold mb-3"
            style={{ color: 'var(--text, #E8EDF5)' }}
          >
            Not Financial Advice
          </h2>
          <p className="text-sm leading-relaxed mb-4" style={{ color: 'var(--text2, #B0C4D8)' }}>
            All content provided on the Rouaa platform — including but not limited to news
            articles, analytical reports, trading signals, market commentary, infographics,
            and economic calendar data — is for informational and educational purposes only.
            Nothing contained on this platform constitutes financial, investment, legal, tax,
            or other professional advice, and should not be relied upon as such.
          </p>
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text2, #B0C4D8)' }}>
            The information presented does not constitute a recommendation, solicitation, or
            offer to buy or sell any financial instruments, including but not limited to
            stocks, bonds, forex, cryptocurrencies, commodities, or derivatives. You should
            always seek the advice of a qualified financial professional before making any
            investment decisions.
          </p>
        </div>

        {/* Sections */}
        {[
          {
            title: 'Trading Signals Disclaimer',
            content: `Trading signals generated by our AI algorithms are based on historical data patterns, technical indicators, and market sentiment analysis. These signals do not guarantee future results and should not be treated as definitive buy or sell recommendations. Signals are provided as one of many possible inputs for your own independent analysis and decision-making process. You are solely responsible for determining whether to act on any signal, and you accept full responsibility for the outcomes of your trading decisions.`,
          },
          {
            title: 'Risk of Loss',
            content: `Financial trading and investing carry inherent risks, including the possibility of losing some or all of your invested capital. The degree of risk varies across different asset classes and market conditions. Leveraged products such as forex, CFDs, and futures carry a high level of risk and may not be suitable for all investors. You should carefully consider your financial situation, investment experience, and risk tolerance before engaging in any trading activity. Past performance — whether simulated or actual — is not indicative of future results.`,
          },
          {
            title: 'Accuracy of Information',
            content: `While we strive to provide accurate, timely, and reliable information, Rouaa makes no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the information, products, services, or related graphics contained on the platform for any purpose. Market data may be delayed, and prices may differ from actual market prices. Any reliance you place on such information is therefore strictly at your own risk.`,
          },
          {
            title: 'AI-Generated Content',
            content: `Portions of the content on this platform are generated or assisted by artificial intelligence systems. While we implement quality controls and editorial oversight, AI-generated content may occasionally contain inaccuracies, omissions, or misinterpretations. You should not rely solely on AI-generated analysis for your investment decisions. Always verify critical information through independent sources and professional advisors before acting on any content found on this platform.`,
          },
          {
            title: 'No Guarantee of Profits',
            content: `Rouaa does not guarantee any specific outcomes, returns, or profits from the use of our platform or services. Any projections, forecasts, or estimates presented are hypothetical in nature and are based on assumptions that may not reflect actual market conditions. There is no guarantee that any particular strategy, signal, or analysis will result in profits or avoid losses. The financial markets are inherently unpredictable, and even the most sophisticated models cannot eliminate the risk of loss.`,
          },
          {
            title: 'Third-Party Content',
            content: `The platform may contain links to or embed content from third-party sources, including news agencies, data providers, and social media platforms. Rouaa does not endorse, verify, or take responsibility for the accuracy, legality, or content of any third-party material. The inclusion of third-party content does not imply endorsement or recommendation. You access third-party content at your own risk.`,
          },
          {
            title: 'Jurisdictional Restrictions',
            content: `The Services provided by Rouaa may not be available or appropriate in all jurisdictions. It is your responsibility to ensure that your use of the platform complies with all applicable local, national, and international laws and regulations. Rouaa makes no representation that the content or services are appropriate or available for use in all locations. If you access the platform from a jurisdiction where financial trading or the provision of financial information is restricted, you do so at your own risk and are solely responsible for compliance with local laws.`,
          },
          {
            title: 'Limitation of Liability',
            content: `To the fullest extent permitted by applicable law, Rouaa, its directors, employees, partners, agents, suppliers, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or other intangible losses, resulting from your access to or use of (or inability to access or use) the platform, any content obtained from the platform, or any conduct or content of any third party on the platform.`,
          },
        ].map(section => (
          <div
            key={section.title}
            className="rounded-2xl p-6 mb-4"
            style={{
              background: 'var(--bg-elevated, rgba(255,255,255,0.04))',
              border: '1px solid var(--border-subtle, rgba(255,255,255,0.08))',
            }}
          >
            <h2
              className="text-base font-bold mb-3"
              style={{ color: 'var(--text, #E8EDF5)' }}
            >
              {section.title}
            </h2>
            <p
              className="text-sm leading-relaxed"
              style={{ color: 'var(--text2, #B0C4D8)' }}
            >
              {section.content}
            </p>
          </div>
        ))}

        {/* Bottom warning */}
        <div
          className="rounded-2xl p-6 text-center"
          style={{
            background: 'rgba(212,175,55,0.04)',
            border: '1px solid rgba(212,175,55,0.15)',
          }}
        >
          <p className="text-sm font-medium mb-2" style={{ color: 'var(--gold, #d4af37)' }}>
            Trade Responsibly
          </p>
          <p className="text-xs leading-relaxed max-w-lg mx-auto" style={{ color: 'var(--text3, #8A9DB2)' }}>
            Always conduct your own research and consult with a licensed financial advisor
            before making investment decisions. Never invest more than you can afford to lose.
          </p>
        </div>
      </div>
    </main>
  );
}
